Repository Qualytics/userguide, pull requests merged in 2024-08, with the labels that each got.

#186 Fixed snowflake image
  docs/assets/datastores/snowflake/finish-configuration-for-existing-enrichment-datastore-light.png
Labels: documentation

#188 SC-17658: Fix the User Guide broken links
  docs/add-datastores/hive.md
  docs/add-datastores/maria-db.md
  docs/add-datastores/presto.md
  docs/add-datastores/qfs.md
  docs/add-datastores/synapse.md
  docs/add-datastores/trino.md
  docs/enrichment/overview-of-an-enrichment-datastore.md
  docs/glossary.md
  docs/technical-quick-start-guide.md
Labels: bug, documentation

#190 SC-17658: Fix Maria DB broken link
  docs/add-datastores/maria-db.md
Labels: bug, documentation

#193 Add some tweaks to integration
  docs/settings/integrations/alation.md
  docs/settings/integrations/atlan.md
Labels: documentation

#191 SC-17713: Add PR Template
  .github/pull_request_template.md
Labels: enhancement

#195 chore: removing content
  .github/pull_request_template.md
Labels: documentation

#201 Updated the "Atlan" document to include details of new features
  docs/assets/integrations/qualytics-add-atlan-integration-dark.png
  docs/assets/integrations/qualytics-add-atlan-integration-light.png
  docs/settings/integrations/atlan.md
Labels: documentation

#211 Updated the screenshots of "Run Instantly" and "Schedule"
  docs/assets/profile-operations/run-dark.png
  docs/assets/profile-operations/run-light.png
  docs/assets/profile-operations/run-now-dark.png
  docs/assets/profile-operations/run-now-light.png
  docs/assets/profile-operations/schedule-dark.png
  docs/assets/profile-operations/schedule-light.png
  docs/source-datastore/profile.md
Labels: documentation

#212 SC-17863: Add release notes for RC 2024.08.19
  docs/changelog.md
Labels: documentation

#213 Screenshot optimization for "Athena"
  docs/assets/datastores/athena/add-configutre-details-dark-4.png
  docs/assets/datastores/athena/add-configutre-details-light-4.png
  docs/assets/datastores/athena/add-datastore-details-dark-2.png
  docs/assets/datastores/athena/add-datastore-details-existing-dark-6.png
  docs/assets/datastores/athena/add-datastore-details-existing-light-6.png
  docs/assets/datastores/athena/add-datastore-details-light-2.png
  docs/assets/datastores/athena/add-enrichment-details-dark-10.png
  docs/assets/datastores/athena/add-enrichment-details-dark-15.png
  docs/assets/datastores/athena/add-enrichment-details-light-10.png
  docs/assets/datastores/athena/add-enrichment-details-light-15.png
  docs/assets/datastores/athena/add-existing-enrichment-dark-16.png
  docs/assets/datastores/athena/add-existing-enrichment-light-16.png
  docs/assets/datastores/athena/add-source-datastore-dark-1.png
  docs/assets/datastores/athena/add-source-datastore-details-dark-3.png
  docs/assets/datastores/athena/add-source-datastore-details-light-3.png
  docs/assets/datastores/athena/add-source-datastore-light-1.png
  docs/assets/datastores/athena/athena-created-dark-14.png
  docs/assets/datastores/athena/athena-created-light-14.png
  docs/assets/datastores/athena/athena-existing-created-dark-19.png
  docs/assets/datastores/athena/athena-existing-created-light-19.png
  docs/assets/datastores/athena/click-finish-dark-17.png
  docs/assets/datastores/athena/click-finish-light-17.png
  docs/assets/datastores/athena/click-source-dark-8.png
  docs/assets/datastores/athena/click-source-light-8.png
  docs/assets/datastores/athena/enrichment-details-dark-9.png
  docs/assets/datastores/athena/enrichment-details-finish-dark-12.png
  docs/assets/datastores/athena/enrichment-details-finish-light-12.png
  docs/assets/datastores/athena/enrichment-details-light-9.png
  docs/assets/datastores/athena/success-connection-dark-13.png
  docs/assets/datastores/athena/success-connection-dark-18.png
  docs/assets/datastores/athena/success-connection-light-13.png
  docs/assets/datastores/athena/success-connection-light-18.png
  docs/assets/datastores/athena/test-enrichment-connection-dark-11.png
  docs/assets/datastores/athena/test-enrichment-connection-light-11.png
  docs/assets/datastores/athena/test-existing-enrichment-connection-dark-7.png
  docs/assets/datastores/athena/test-existing-enrichment-connection-light-7.png
  docs/assets/datastores/athena/test-source-connection-dark-5.png
  docs/assets/datastores/athena/test-source-connection-light-5.png
Labels: documentation
