Repository Qualytics/userguide, pull requests merged in 2024-10, with the labels that each got.

#276 SC-18449: Update `Notifications Overview` file as per the latest release
  docs/assets/notifications/message-dark.png
  docs/assets/notifications/message-light.png
  docs/assets/notifications/name-description-dark.png
  docs/assets/notifications/name-description-light.png
  docs/assets/notifications/notification-window-dark-5.png
  docs/assets/notifications/notification-window-light-5.png
  docs/assets/notifications/notifications-dark-1.png
  docs/assets/notifications/notifications-light-1.png
  docs/assets/notifications/save-dark-9.png
  docs/assets/notifications/save-light-9.png
  docs/assets/notifications/select-channel-dark-8.png
  docs/assets/notifications/select-channel-light-8.png
  docs/assets/notifications/trigger-condition-dark.png
  docs/assets/notifications/trigger-condition-light.png
  docs/notifications/overview-of-a-notification.md
Labels: documentation

#277 SC-18449: Update `Manage Notifications` file as per the latest release
  docs/assets/notifications/manage-notifications/edit-button-dark-10.png
  docs/assets/notifications/manage-notifications/edit-button-light-10.png
  docs/assets/notifications/manage-notifications/edit-notification-rule-dark-11.png
  docs/assets/notifications/manage-notifications/edit-notification-rule-dark-18.png
  docs/assets/notifications/manage-notifications/edit-notification-rule-light-11.png
  docs/assets/notifications/manage-notifications/edit-notification-rule-light-18.png
  docs/assets/notifications/manage-notifications/mute-button-dark-24.png
  docs/assets/notifications/manage-notifications/mute-button-light-24.png
  docs/assets/notifications/manage-notifications/muted-notifi-dark-25.png
  docs/assets/notifications/manage-notifications/muted-notifi-light-25.png
  docs/assets/notifications/manage-notifications/notification-categorized-dark-3.png
  docs/assets/notifications/manage-notifications/notification-categorized-light-3.png
  docs/assets/notifications/manage-notifications/notification-triggered-dark-2.png
  docs/assets/notifications/manage-notifications/notification-triggered-dark-22.png
  docs/assets/notifications/manage-notifications/notification-triggered-dark-8.png
  docs/assets/notifications/manage-notifications/notification-triggered-light-2.png
  docs/assets/notifications/manage-notifications/notification-triggered-light-22.png
  docs/assets/notifications/manage-notifications/notification-triggered-light-8.png
  docs/assets/notifications/manage-notifications/save-button-dark-12.png
  docs/assets/notifications/manage-notifications/save-button-dark-19.png
  docs/assets/notifications/manage-notifications/save-button-light-12.png
  docs/assets/notifications/manage-notifications/save-button-light-19.png
  docs/assets/notifications/manage-notifications/unmuted-button-dark-31.png
  docs/assets/notifications/manage-notifications/unmuted-button-light-31.png
  docs/assets/notifications/manage-notifications/vertical-ellipsis-dark-23.png
  docs/assets/notifications/manage-notifications/vertical-ellipsis-dark-9.png
  docs/assets/notifications/manage-notifications/vertical-ellipsis-light-23.png
  docs/assets/notifications/manage-notifications/vertical-ellipsis-light-9.png
  docs/notifications/managing-notifications.md
Labels: documentation

#278 SC-18449: Update `Email Notification` file as per the latest release.
  docs/assets/notifications/services/email/email-channel-dark-8.png
  docs/assets/notifications/services/email/email-channel-light-8.png
  docs/assets/notifications/services/email/message-dark-6.png
  docs/assets/notifications/services/email/message-light-6.png
  docs/assets/notifications/services/email/modal-window-dark-4.png
  docs/assets/notifications/services/email/modal-window-light-4.png
  docs/assets/notifications/services/email/name-description-dark.png
  docs/assets/notifications/services/email/name-description-light.png
  docs/assets/notifications/services/email/save-button-dark-11.png
  docs/assets/notifications/services/email/save-button-light-11.png
  docs/assets/notifications/services/email/test-notification-dark-9.png
  docs/assets/notifications/services/email/test-notification-light-9.png
  docs/assets/notifications/services/email/trigger-condition-dark-5.png
  docs/assets/notifications/services/email/trigger-condition-light-5.png
  docs/notifications/notification-services/email.md
Labels: documentation

#279 SC-18449: Update `HTTP Action` file as per the latest release.
  docs/assets/notifications/services/http-action/details-dark-10.png
  docs/assets/notifications/services/http-action/details-dark-11.png
  docs/assets/notifications/services/http-action/details-dark-9.png
  docs/assets/notifications/services/http-action/details-light-10.png
  docs/assets/notifications/services/http-action/details-light-11.png
  docs/assets/notifications/services/http-action/details-light-9.png
  docs/assets/notifications/services/http-action/enter-details-dark-5.png
  docs/assets/notifications/services/http-action/enter-details-dark-55.png
  docs/assets/notifications/services/http-action/enter-details-light-5.png
  docs/assets/notifications/services/http-action/enter-details-light-55.png
  docs/assets/notifications/services/http-action/message-dark-6.png
  docs/assets/notifications/services/http-action/message-light-6.png
  docs/assets/notifications/services/http-action/modal-window-dark-4.png
  docs/assets/notifications/services/http-action/modal-window-light-4.png
  docs/assets/notifications/services/http-action/notification-channel-dark-8.png
  docs/assets/notifications/services/http-action/notification-channel-light-8.png
  docs/notifications/notification-services/http-action.md
  docs/notifications/overview-of-a-notification.md
Labels: documentation

#285 SC-18500: Release 2024.10.04
  docs/changelog.md
Labels: documentation

#286 SC-18515: Fix `Connections Overview` user guide broken images link .
  docs/assets/connections/connection/add-datastore-connection-modal-dark.png
  docs/assets/connections/connection/add-datastore-connection-modal-light.png
  docs/assets/connections/connection/add-datastore-modal-dark.png
  docs/assets/connections/connection/add-datastore-modal-light.png
  docs/assets/connections/connection/connections-list-dark.png
  docs/assets/connections/connection/connections-list-light.png
  docs/connections/overview-of-a-connection.md
Labels: bug, documentation

#281 SC-18449: Update `PagerDuty` Notification userguide based on the latest release
  docs/assets/notifications/services/pagerduty/channel-dark-8.png
  docs/assets/notifications/services/pagerduty/channel-light-8.png
  docs/assets/notifications/services/pagerduty/conditions-dark-5.png
  docs/assets/notifications/services/pagerduty/conditions-light-5.png
  docs/assets/notifications/services/pagerduty/message-dark-6.png
  docs/assets/notifications/services/pagerduty/message-light-6.png
  docs/assets/notifications/services/pagerduty/name-description-dark.png
  docs/assets/notifications/services/pagerduty/name-description-light.png
  docs/assets/notifications/services/pagerduty/notification-rule-dark-4.png
  docs/assets/notifications/services/pagerduty/notification-rule-light-4.png
  docs/assets/notifications/services/pagerduty/save-dark-11.png
  docs/assets/notifications/services/pagerduty/save-light-11.png
  docs/assets/notifications/services/pagerduty/severity-dark-9.png
  docs/assets/notifications/services/pagerduty/severity-light-9.png
  docs/assets/notifications/services/pagerduty/test-dark-10.png
  docs/assets/notifications/services/pagerduty/test-light-10.png
  docs/notifications/notification-services/pagerduty.md
Labels: documentation

#283 SC-18449: Update Webhook Notification userguide based on the latest release.
  docs/assets/notifications/services/webhook/add-notification-dark-3.png
  docs/assets/notifications/services/webhook/add-notification-light-3.png
  docs/assets/notifications/services/webhook/channel-dark-9.png
  docs/assets/notifications/services/webhook/channel-light-9.png
  docs/assets/notifications/services/webhook/conditions-dark-6.png
  docs/assets/notifications/services/webhook/conditions-light-6.png
  docs/assets/notifications/services/webhook/message-dark-7.png
  docs/assets/notifications/services/webhook/message-light-7.png
  docs/assets/notifications/services/webhook/name-dark-5.png
  docs/assets/notifications/services/webhook/name-light-5.png
  docs/assets/notifications/services/webhook/notification-rule-dark-4.png
  docs/assets/notifications/services/webhook/notification-rule-light-4.png
  docs/assets/notifications/services/webhook/save-dark-12.png
  docs/assets/notifications/services/webhook/save-light-12.png
  docs/assets/notifications/services/webhook/setting-dark-1.png
  docs/assets/notifications/services/webhook/setting-light-1.png
  docs/assets/notifications/services/webhook/tag-dark-8.png
  docs/assets/notifications/services/webhook/tag-light-8.png
  docs/assets/notifications/services/webhook/test-dark-10.png
  docs/assets/notifications/services/webhook/test-light-10.png
  docs/notifications/notification-services/webhook.md
Labels: documentation

#282 SC-18449: Update `Slack Notification` userguide based on the latest release.
  docs/assets/notifications/services/slack/add-notification-dark-3.png
  docs/assets/notifications/services/slack/add-notification-light-3.png
  docs/assets/notifications/services/slack/enter-details-dark-5.png
  docs/assets/notifications/services/slack/enter-details-dark-55.png
  docs/assets/notifications/services/slack/enter-details-light-5.png
  docs/assets/notifications/services/slack/enter-details-light-55.png
  docs/assets/notifications/services/slack/message-dark-6.png
  docs/assets/notifications/services/slack/message-light-6.png
  docs/assets/notifications/services/slack/modal-window-dark-4.png
  docs/assets/notifications/services/slack/modal-window-light-4.png
  docs/assets/notifications/services/slack/save-button-dark-11.png
  docs/assets/notifications/services/slack/save-button-light-11.png
  docs/assets/notifications/services/slack/settings-dark-1.png
  docs/assets/notifications/services/slack/settings-light-1.png
  docs/assets/notifications/services/slack/slack-channel-dark-8.png
  docs/assets/notifications/services/slack/slack-channel-light-8.png
  docs/assets/notifications/services/slack/test-notification-dark-9.png
  docs/assets/notifications/services/slack/test-notification-light-9.png
  docs/notifications/notification-services/slack.md
Labels: documentation

#284 SC-18449: Update Health userguide based on the latest release.
  docs/assets/health/copied-dark-7.png
  docs/assets/health/copied-light-7.png
  docs/assets/health/copy-health-dark-6.png
  docs/assets/health/copy-health-light-6.png
  docs/assets/health/global-settings-dark-1.png
  docs/assets/health/global-settings-light-1.png
  docs/assets/health/health-dark-2.png
  docs/assets/health/health-indicator-dark-4.png
  docs/assets/health/health-indicator-light-4.png
  docs/assets/health/health-light-2.png
  docs/assets/health/refresh-health-dark-8.png
  docs/assets/health/refresh-health-light-8.png
  docs/assets/health/restart-analytics-dark-9.png
  docs/assets/health/restart-analytics-light-9.png
  docs/assets/health/summary-dark-3.png
  docs/assets/health/summary-light-3.png
  docs/settings/health/overview-of-health.md
Labels: documentation

#296 SC-18632: Release 2024.10.04
  docs/changelog.md
Labels: documentation

#307 SC-18735: Release 2024.10.23
  docs/changelog.md
Labels: documentation

#309 SC-18758: Issue on printing User Guide
  mkdocs.yml
Labels: bug
