Repository Qualytics/userguide, pull requests merged in 2025-06, with the labels that each got.

#695 QUA-604: Update "Status" userguide.
  docs/assets/health/successfully-triggered-dark-11.png
  docs/assets/health/successfully-triggered-light-11.png
Labels: documentation

#699 Qua-605 Update Teradata userguide.
  docs/add-datastores/teradata.md
Labels: documentation

#700 QUA-605: Update "Field Count Check" userguide.
  docs/checks/field-count-check.md
Labels: documentation

#701 QUA-605: Update"Maria DB" userguide.
  docs/add-datastores/maria-db.md
Labels: documentation

#706 QUA-605: Update "Manage Tables and Files" userguides
  docs/container/manage-tables-and-files.md
Labels: documentation

#708 QUA:605-Update "Apply Check Template For Quality Checks" userguide.
  docs/checks/apply-check-template-for-quality-checks.md
Labels: documentation

#710 QUA:605-Fix "Snowflake" userguide.
  docs/add-datastores/snowflake.md
Labels: documentation

#712 QUA:605- Update "Token" userguide.
  docs/settings/tokens/overview-of-tokens.md
Labels: documentation

#711 QUA:605- Update "PostgreSQL" userguide.
  docs/add-datastores/postgresql.md
Labels: documentation

#717 QUA-605: Update "Token" userguide as per latest release.
  docs/assets/tokens/click-delete-dark-14.png
  docs/assets/tokens/click-delete-light-14.png
Labels: documentation

#719 QUA-627: Update "Scan Operation" file as per the latest release.
  docs/source-datastore/scan.md
Labels: documentation

#723 Fix: Title and move the section
  docs/integrations/alerting/msft_teams.md
Labels: bug

#725 QUA-617: v2025.6.13
  docs/changelog.md
Labels: release notes

#732 QUA-649: Update "Tokens" userguide.
  docs/assets/tokens/click-delete-dark-14.png
  docs/assets/tokens/click-delete-light-14.png
  docs/assets/tokens/delete-window-dark-13.png
  docs/assets/tokens/delete-window-light-13.png
Labels: documentation

#733 QUA-656: v2025.6.20
  docs/changelog.md
Labels: release notes

#728 QUA-649: Update "Manage Checks" userguide as per the latest release.
  docs/assets/datastore-checks/manage-checks/anomalies-dark.png
  docs/assets/datastore-checks/manage-checks/anomalies-light.png
  docs/assets/datastore-checks/manage-checks/click-check-dark.png
  docs/assets/datastore-checks/manage-checks/click-check-light.png
  docs/assets/datastore-checks/manage-checks/download-records-dark.png
  docs/assets/datastore-checks/manage-checks/download-records-light.png
  docs/assets/datastore-checks/manage-checks/dry-run-dark.png
  docs/assets/datastore-checks/manage-checks/dry-run-light.png
  docs/assets/datastore-checks/manage-checks/fields-dark-1.png
  docs/assets/datastore-checks/manage-checks/fields-dark.png
  docs/assets/datastore-checks/manage-checks/fields-light-1.png
  docs/assets/datastore-checks/manage-checks/fields-light.png
  docs/assets/datastore-checks/manage-checks/results-dark.png
  docs/assets/datastore-checks/manage-checks/results-light.png
  docs/assets/datastore-checks/manage-checks/sort-options-dark.png
  docs/assets/datastore-checks/manage-checks/sort-options-light.png
  docs/assets/datastore-checks/manage-checks/source-records-dark.png
  docs/assets/datastore-checks/manage-checks/source-records-light.png
  docs/datastore-checks/manage-checks.md
Labels: documentation

#737 QUA-649: Update "Anomaly Analysis" userguide as per the latest release.
  docs/anomalies/anomalies.md
  docs/assets/datastores/anomalies/anomalies-action-dark.png
  docs/assets/datastores/anomalies/anomalies-action-light.png
  docs/assets/datastores/anomalies/anomalies-details-dark.png
  docs/assets/datastores/anomalies/anomalies-details-light.png
  docs/assets/datastores/anomalies/details-dark.png
  docs/assets/datastores/anomalies/details-light.png
Labels: documentation

#738 QUA-627: Update "Catalog Operation" userguide as per the latest release.
  docs/assets/catalog-operations/add-source-datastore-dark.png
  docs/assets/catalog-operations/add-source-datastore-light.png
  docs/assets/catalog-operations/catalog-dark.png
  docs/assets/catalog-operations/catalog-light.png
  docs/source-datastore/catalog.md
Labels: documentation
