Repository Qualytics/userguide, pull requests merged in 2025-09, with the labels that each got.

#818 QUA-840: Update "Redshift" userguide.
  docs/add-datastores/redshift.md
  docs/assets/datastores/redshift/add-datastore-credentials-dark.png
  docs/assets/datastores/redshift/add-datastore-credentials-explain-dark.png
  docs/assets/datastores/redshift/add-datastore-credentials-explain-new-dark.png
  docs/assets/datastores/redshift/add-datastore-dark.png
  docs/assets/datastores/redshift/add-enrichment-dark.png
  docs/assets/datastores/redshift/add-enrichment-detail-dark.png
  docs/assets/datastores/redshift/add-enrichment-details-dark.png
  docs/assets/datastores/redshift/data-operation-page-dark.png
  docs/assets/datastores/redshift/enrichment-datastore-explain-dark.png
  docs/assets/datastores/redshift/finish-configuration-dark.png
  docs/assets/datastores/redshift/finish-configuration-for-existing-enrichment-datastore-dark.png
  docs/assets/datastores/redshift/hashcorp-explain-dark.png
  docs/assets/datastores/redshift/next-button-for-enrichment-dark.png
  docs/assets/datastores/redshift/secret-management-dark.png
  docs/assets/datastores/redshift/select-a-connector-dark.png
  docs/assets/datastores/redshift/select-enrichment-connector-dark.png
  docs/assets/datastores/redshift/select-existing-enrichment-datastore-dark.png
  docs/assets/datastores/redshift/success-message-dark.png
  docs/assets/datastores/redshift/success-message-light.png
  docs/assets/datastores/redshift/test-connection-for-enrichment-datastore-dark.png
  docs/assets/datastores/redshift/test-connection-for-existing-datastore-dark.png
  docs/assets/datastores/redshift/test-datastore-connection-dark.png
  docs/assets/datastores/redshift/use-enrichment-dark.png
  docs/assets/datastores/redshift/use-existing-datastore-dark.png
  docs/assets/datastores/redshift/use-existing-enrichment-datastore-dark.png
Labels: documentation

#820 QUA-911: v2025.9.4
  docs/changelog.md
Labels: release notes

#824 QUA-840: Update "Teradata" userguide.
  docs/add-datastores/teradata.md
  docs/assets/datastores/teradata/add-configutre-details-dark-4.png
  docs/assets/datastores/teradata/add-connection-details-dark-3.png
  docs/assets/datastores/teradata/add-enrichment-dark.png
  docs/assets/datastores/teradata/add-enrichment-details-dark-9.png
  docs/assets/datastores/teradata/add-enrichment-details-dark.png
  docs/assets/datastores/teradata/add-enrichment-details-existing-dark-15.png
  docs/assets/datastores/teradata/add-source-datastore-dark-1.png
  docs/assets/datastores/teradata/add-source-teradata-dark-1.png
  docs/assets/datastores/teradata/add-teradata-connection-dark-2.png
  docs/assets/datastores/teradata/enrichment-details-added-dark-10.png
  docs/assets/datastores/teradata/enrichment-details-check-dark-16.png
  docs/assets/datastores/teradata/enrichment-details-finish-dark-17.png
  docs/assets/datastores/teradata/enrichment-details-success-dark-18.png
  docs/assets/datastores/teradata/enrichment-details-success-light-18.png
  docs/assets/datastores/teradata/enrichment-next-dark-8.png
  docs/assets/datastores/teradata/enter-teradata-details-dark-4.png
  docs/assets/datastores/teradata/existing-connection-teradata-dark-6.png
  docs/assets/datastores/teradata/hashcorp-explain-dark.png
  docs/assets/datastores/teradata/source-datastore-teradata-overview-dark-14.png
  docs/assets/datastores/teradata/success-connection-teradata-dark-13.png
  docs/assets/datastores/teradata/success-connection-teradata-light-13.png
  docs/assets/datastores/teradata/teradata-source-overview-dark-19.png
  docs/assets/datastores/teradata/test-connection-success-existing-dark-7.png
  docs/assets/datastores/teradata/test-connection-success-new-dark-5.png
  docs/assets/datastores/teradata/test-enrichment-finish-dark-12.png
  docs/assets/datastores/teradata/test-enrichment-success-dark-11.png
  docs/assets/datastores/teradata/use-enrichment-dark.png
Labels: documentation

#826 QUA-928: Remove UDF ruletype
  docs/checks/user-defined-function-check.md
  mkdocs.yml
Labels: documentation

#829 Qua 943 update the is replica of warning message
  docs/anomalies/source-record.md
  docs/checks/data-diff-check.md
  docs/checks/is-replica-of-check.md
  docs/checks/overview-of-a-check.md
  docs/checks/rule-types-overview.md
  docs/source-datastore/profile.md
  docs/weight/weighting.md
  mkdocs.yml
Labels: documentation, enhancement

#833 QUA-945: Update the "Container" userguide as per your suggestions.
  docs/assets/container/containers/change-light.png
  docs/container/container.md
Labels: documentation

#834 QUA-840: Update "MariaDB" userguide.
  docs/add-datastores/maria-db.md
  docs/assets/datastores/maria-db/Untitled document (2).pdf-image-042.png
  docs/assets/datastores/maria-db/Untitled document (2).pdf-image-043.png
  docs/assets/datastores/maria-db/Untitled document (2).pdf-image-044.png
  docs/assets/datastores/maria-db/Untitled document (2).pdf-image-045.png
  docs/assets/datastores/maria-db/add-dark.png
  docs/assets/datastores/maria-db/caret-dark.png
  docs/assets/datastores/maria-db/carett-dark.png
  docs/assets/datastores/maria-db/connections-dark.png
  docs/assets/datastores/maria-db/connector-dark.png
  docs/assets/datastores/maria-db/create-datastore-dark.png
  docs/assets/datastores/maria-db/datastore-dark.png
  docs/assets/datastores/maria-db/details-dark.png
  docs/assets/datastores/maria-db/enrichment-light.png
  docs/assets/datastores/maria-db/enrichmnet-dark.png
  docs/assets/datastores/maria-db/finish-dark.png
  docs/assets/datastores/maria-db/finishh-dark.png
  docs/assets/datastores/maria-db/form-dark.png
  docs/assets/datastores/maria-db/modal-dark.png
  docs/assets/datastores/maria-db/msg-dark.png
  docs/assets/datastores/maria-db/msg-light.png
  docs/assets/datastores/maria-db/next-dark.png
  docs/assets/datastores/maria-db/operatons-dark.png
  docs/assets/datastores/maria-db/secret-dark.png
  docs/assets/datastores/maria-db/test-dark.png
  docs/assets/datastores/maria-db/tests-dark.png
  docs/assets/datastores/maria-db/testss-dark.png
  docs/assets/datastores/maria-db/windoww-dark.png
  docs/assets/datastores/maria-db/windowww-dark.png
Labels: documentation

#838 QUA-972: Update "Link enrichment" userguide as per the latest release.
  docs/assets/datastore-settings/link-enrichment/link-enrichment-light-7.png
  docs/assets/datastore-settings/link-enrichment/modal-light.png
  docs/assets/datastore-settings/link-enrichment/window-light.png
  docs/source-datastore/link-enrichment.md
Labels: documentation

#837 QUA-977: Add "Keyboard shortcuts" userguide as per latest release.
  docs/assets/keyboard-shortcuts/click-search-key-shortcuts.png
  docs/assets/keyboard-shortcuts/keyboard-shortcuts.png
  docs/assets/keyboard-shortcuts/search-key-shortcuts.png
  docs/assets/keyboard-shortcuts/search-options.png
  docs/assets/keyboard-shortcuts/search.png
  docs/keyboard-shortcuts.md
  mkdocs.yml
Labels: documentation

#843 QUA-1001: Add Enrichment Support column to all Source Datastore matrices
  docs/add-datastores/overview-of-a-datastore.md
  docs/add-datastores/source-datastore.md
  docs/enrichment-support/supported-enrichment-datastores.md
  mkdocs.yml
Labels: bug

#842 QUA-994: Update "Scheduled Operation" userguide as per the suggestions.
  docs/operation-automation/automated-setup-using-qualytics-cli.md
  docs/operation-automation/automated-tasks-with-cron.md
  docs/operation-automation/linux-machine.md
  docs/operation-automation/overview.md
  docs/operation-automation/windows-machine.md
  mkdocs.yml
Labels: documentation
