Repository Qualytics/userguide, pull requests merged in 2025-02, with the labels that each got.

#482 Qua156: Update "Overview" document as per the latest release.
  docs/assets/enrichment/overview-enrichment/click-dark.png
  docs/assets/enrichment/overview-enrichment/click-light.png
Labels: documentation

#481 Qua156: Update "Add Enrichment " user guide as per the latest release.
  docs/assets/enrichment/add-enrichment/enrichment-dark.png
  docs/assets/enrichment/add-enrichment/enrichment-light.png
Labels: documentation

#480 Qua156: Update "Data Preview" user guide as per the latest release.
  docs/assets/enrichment/data-preview/click-dark.png
  docs/assets/enrichment/data-preview/click-light.png
Labels: documentation

#478 Qua156: Update "Datastore Setting" userguide as per the latest release.
  docs/assets/datastore-settings/add-datastore-dark-1.png
  docs/assets/datastore-settings/add-datastore-light-1.png
Labels: documentation

#477 Qua156: Update "External Scan" userguide as per the latest release.
  docs/assets/external-scan/datastore-dark-1.png
  docs/assets/external-scan/datastore-light-1.png
Labels: documentation

#458 Qua-156: Update data source user guide as the per the release
  docs/add-datastores/overview-of-a-datastore.md
  docs/assets/datastores/what-is/activity-dark-6.png
  docs/assets/datastores/what-is/activity-light-6.png
  docs/assets/datastores/what-is/add-dark-1.png
  docs/assets/datastores/what-is/add-light-1.png
  docs/assets/datastores/what-is/connector-dark-2.png
  docs/assets/datastores/what-is/connector-light-2.png
  docs/assets/datastores/what-is/datastore.png
  docs/assets/datastores/what-is/detail-dark-3.png
  docs/assets/datastores/what-is/detail-light-3.png
  docs/assets/datastores/what-is/home-dark-4.png
  docs/assets/datastores/what-is/home-dark-5.png
  docs/assets/datastores/what-is/home-light-4.png
  docs/assets/datastores/what-is/home-light-5.png
Labels: documentation

#460 Qua-273: Added logos to analytics userguide
  docs/assets/analytics/power-1.png
  docs/assets/analytics/sigma-dark-2.png
  docs/assets/analytics/sigma-light-2.png
  docs/assets/analytics/tableau-3.png
  docs/integrations/analytics.md
Labels: documentation

#459 Qua-273: Add logos in workflow user guide
  docs/assets/workflow/airflow-dark.png
  docs/assets/workflow/airflow-light.png
  docs/assets/workflow/dbt-dark.png
  docs/assets/workflow/dbt-light.png
  docs/integrations/workflow.md
Labels: documentation

#484 QUA-156: Update "Manage Tables and Files" as per the latest release.
  docs/assets/container/manage-tables-files/excluding-dark-100.png
  docs/assets/container/manage-tables-files/excluding-light-100.png
  docs/assets/container/manage-tables-files/general-dark-111.png
  docs/assets/container/manage-tables-files/general-dark-112.png
  docs/assets/container/manage-tables-files/general-dark-113.png
  docs/assets/container/manage-tables-files/general-dark-114.png
  docs/assets/container/manage-tables-files/general-light-111.png
  docs/assets/container/manage-tables-files/general-light-112.png
  docs/assets/container/manage-tables-files/general-light-113.png
  docs/assets/container/manage-tables-files/general-light-114.png
  docs/assets/container/manage-tables-files/group-dark-99.png
  docs/assets/container/manage-tables-files/group-light-99.png
  docs/assets/container/manage-tables-files/save-dark-122.png
  docs/assets/container/manage-tables-files/save-light-122.png
  docs/assets/container/manage-tables-files/setting-dark-44.png
  docs/assets/container/manage-tables-files/setting-light-44.png
  docs/assets/container/manage-tables-files/success-dark-133.png
  docs/assets/container/manage-tables-files/success-light-133.png
  docs/assets/container/manage-tables-files/table-settings-dark-55.png
  docs/assets/container/manage-tables-files/table-settings-light-55.png
  docs/container/manage-tables-and-files.md
Labels: documentation

#489 QUA-318: Warning messages from user guide project
  docs/changelog.md
  docs/glossary.md
Labels: bug

#487 QUA-319: RC 2025.02.06
  docs/changelog.md
Labels: release notes

#493 QUA-318: Update "Connection Overview" Document.
  docs/connections/overview-of-a-connection.md
Labels: bug

#492 Qua318: Update "Synapse" userguide .
  docs/add-datastores/synapse.md
Labels: documentation

#495 Qua325: Update "Overview" document under Security section as per the latest release.
  docs/assets/security/click-delete-dark-24.png
  docs/assets/security/click-delete-light-24.png
  docs/assets/security/user-updated-dark-11.png
  docs/assets/security/user-updated-light-11.png
  docs/settings/security/overview.md
Labels: documentation

#498 Qua326: Fix the broken link on "Explore" userguide.
  docs/explore/overview-of-explore.md
Labels: documentation

#499 Qua326: Fix "Checks Overview" File Broken Links.
  docs/checks/overview-of-a-check.md
Labels: documentation

#500 Qua326: Fix the "Deployments Options" user guide broken links.
  docs/deployments/deployments.md
Labels: documentation

#501 Qua326: Fix the broken Link on "Enrichment Datastore Overview File".
  docs/enrichment/overview-of-an-enrichment-datastore.md
Labels: documentation

#496 QUA-315: Update "Insights" userguide as per the latest release.
  docs/assets/explore/insights/acknowledged-anomalies-13-dark.png
  docs/assets/explore/insights/acknowledged-anomalies-13-light.png
  docs/assets/explore/insights/active-anomalies-12-dark.png
  docs/assets/explore/insights/active-anomalies-12-light.png
  docs/assets/explore/insights/anomalies-11-dark.png
  docs/assets/explore/insights/anomalies-11-light.png
  docs/assets/explore/insights/authored-dark.png
  docs/assets/explore/insights/authored-light.png
  docs/assets/explore/insights/checks-7-dark.png
  docs/assets/explore/insights/checks-7-light.png
  docs/assets/explore/insights/download-29-dark.png
  docs/assets/explore/insights/download-29-light.png
  docs/assets/explore/insights/export-28-dark.png
  docs/assets/explore/insights/export-28-light.png
  docs/assets/explore/insights/failed-check-9-dark.png
  docs/assets/explore/insights/failed-check-9-light.png
  docs/assets/explore/insights/filter-3-dark.png
  docs/assets/explore/insights/filter-3-light.png
  docs/assets/explore/insights/inferred-dark.png
  docs/assets/explore/insights/inferred-light.png
  docs/assets/explore/insights/insights-2-dark.png
  docs/assets/explore/insights/insights-2-light.png
  docs/assets/explore/insights/not-asserted-10-dark.png
  docs/assets/explore/insights/not-asserted-10-light.png
  docs/assets/explore/insights/overview-5-dark.png
  docs/assets/explore/insights/overview-5-light.png
  docs/assets/explore/insights/passed-check-8-dark.png
  docs/assets/explore/insights/passed-check-8-light.png
  docs/assets/explore/insights/quality-4-dark.png
  docs/assets/explore/insights/quality-4-light.png
  docs/assets/explore/insights/records-6-dark.png
  docs/assets/explore/insights/records-6-light.png
  docs/assets/explore/insights/resolved-anomalies-14-dark.png
  docs/assets/explore/insights/resolved-anomalies-14-light.png
  docs/assets/explore/insights/rule-type-15-dark.png
  docs/assets/explore/insights/rule-type-15-light.png
  docs/assets/explore/insights/top-16-dark.png
  docs/assets/explore/insights/top-16-light.png
  docs/explore/insights.md
Labels: documentation

#503 QUA-334: Update "Tags" file as per the latest release.
  docs/assets/tags/tags-dark-1.png
  docs/assets/tags/tags-light-1.png
Labels: documentation

#507 QUA-336: RC2025.02.13
  docs/changelog.md
Labels: release notes

#505 Qua334: Update "Manage Check" file as per the latest release.
  docs/assets/checks/manage-checks/datastore-dark-1.png
  docs/assets/checks/manage-checks/datastore-light-1.png
Labels: documentation

#508 QUA-334: Update"Tokens"File as per the latest release.
  docs/assets/tokens/global-setting-dark-1.png
  docs/assets/tokens/global-setting-light-1.png
Labels: documentation

#509 QUA-334: Update "Profiles" as per the latest release.
  docs/assets/explore/profiles/explore-dark.png
  docs/assets/explore/profiles/explore-light.png
Labels: documentation

#510 QUA-334: Update "Checks" File as per the latest release.
  docs/assets/explore/checks/explore-dark.png
  docs/assets/explore/checks/explore-light.png
Labels: documentation

#504 QUA-335:Add "Freshness Check" under rule types.
  docs/assets/checks/freshness-check/add-dark.png
  docs/assets/checks/freshness-check/add-light.png
  docs/assets/checks/freshness-check/fields-dark.png
  docs/assets/checks/freshness-check/fields-light.png
  docs/assets/checks/freshness-check/save-dark.png
  docs/assets/checks/freshness-check/save-light.png
  docs/assets/checks/freshness-check/select-dark.png
  docs/assets/checks/freshness-check/select-light.png
  docs/assets/checks/freshness-check/success-dark.png
  docs/assets/checks/freshness-check/success-light.png
  docs/assets/checks/freshness-check/validate-dark.png
  docs/assets/checks/freshness-check/validate-light.png
  docs/assets/checks/freshness-check/validatebtn-dark.png
  docs/assets/checks/freshness-check/validatebtn-light.png
  docs/assets/checks/freshness-check/window-dark.png
  docs/assets/checks/freshness-check/window-light.png
  docs/checks/freshness-check.md
  mkdocs.yml
Labels: documentation

#512 QUA-341: Updated the theam section as per the latest release
  docs/web-app.md
Labels: documentation

#511 QUA-346: Divided the changelog by year
  docs/changelog2023.md
  docs/changelog2024.md
  docs/changelog2025.md
  mkdocs.yml
Labels: documentation

#515 QUA-350: Updated "Scan" operation document
  docs/assets/datastores/scan/side-menu-dark.png
  docs/assets/datastores/scan/side-menu-light.png
  docs/assets/scan/side-menu-dark.png
  docs/assets/scan/side-menu-light.png
Labels: documentation

#517 QUA-357: Updated "Computed Fields" document
  docs/assets/container/computed-field/container-dark-2.png
  docs/assets/container/computed-field/container-light-2.png
  docs/assets/container/computed-field/datastore-dark-1.png
  docs/assets/container/computed-field/datastore-light-1.png
  docs/assets/container/computed-field/explore-dark.png
  docs/assets/container/computed-field/explore-light.png
  docs/assets/container/computed-field/field-created-dark-8.png
  docs/assets/container/computed-field/field-created-light-8.png
  docs/assets/container/computed-field/team-dark.png
  docs/assets/container/computed-field/team-light.png
Labels: documentation

#519 QUA-358: Updated "Export Metadata" Document
  docs/assets/container/export-metadata/covid-19-dark-2.png
  docs/assets/container/export-metadata/covid-19-light-2.png
  docs/assets/container/export-metadata/enrichment-dark-10.png
  docs/assets/container/export-metadata/enrichment-light-10.png
  docs/assets/container/export-metadata/export-metadata-dark-3.png
  docs/assets/container/export-metadata/export-metadata-light-3.png
  docs/assets/container/export-metadata/exported-dark-11.png
  docs/assets/container/export-metadata/exported-light-11.png
  docs/assets/container/export-metadata/select-source-dark-1.png
  docs/assets/container/export-metadata/select-source-light-1.png
Labels: documentation

#520 QUA-360: Fix release notes url
  docs/changelog-2023.md
  docs/changelog-2024.md
  docs/changelog.md
  mkdocs.yml
Labels: bug

#524 QUA-363: Updated Containers Settings>"Grouping" document
  docs/assets/identifiers/grouping-overview/datastore-dark.png
  docs/assets/identifiers/grouping-overview/datastore-light.png
Labels: documentation

#523 Updated Container Settings>"General" Document
  docs/assets/identifiers/general-overview/datastore-dark.png
  docs/assets/identifiers/general-overview/datastore-light.png
Labels: documentation

#522 QUA-365: Updated Data Quality Check "Overview" document
  docs/assets/checks/checks-overview/datastores-dark-1.png
  docs/assets/checks/checks-overview/datastores-light-1.png
  docs/assets/checks/checks-overview/explore-dark-5.png
  docs/assets/checks/checks-overview/explore-light-5.png
Labels: documentation

#521 QUA-355: Updated "Data Preview" document
  docs/assets/container/data-preview/alter-dark.png
  docs/assets/container/data-preview/alter-light.png
  docs/assets/container/data-preview/select-dark.png
  docs/assets/container/data-preview/select-light.png
Labels: documentation

#527 QUA-370: Update "Computed Tables and Files" userguide as per the latest release.
  docs/assets/datastores/add-computed-tables-files/select-datastore-dark.png
  docs/assets/datastores/add-computed-tables-files/select-datastore-light.png
Labels: documentation

#525 QUA-370: Update "Anomalies" File under explore section as per the latest release.
  docs/assets/explore/anomalies/explore-dark.png
  docs/assets/explore/anomalies/explore-light.png
Labels: documentation

#530 QUA-370: Update"Export Check Templates" userguide.
  docs/assets/checks/export-check-templates/enrichment-datastore-dark-6.png
  docs/assets/checks/export-check-templates/enrichment-datastore-light-6.png
  docs/assets/checks/export-check-templates/library-dark-1.png
  docs/assets/checks/export-check-templates/library-light-1.png
Labels: documentation

#528 Qua372: Create a Document "Enrichment Support Datastores".
  docs/enrichment-support/enrichment-support-datastores.md
  mkdocs.yml
Labels: documentation

#529 QUA-370: Update "Authored Check" File as per the latest release.
  docs/assets/checks/authored-checks/datastore-dark.png
  docs/assets/checks/authored-checks/datastore-light.png
Labels: documentation

#532 QUA-370:Update "Inferred Check" File as per the latest release.
  docs/assets/checks/inferred-checks/datastore-dark.png
  docs/assets/checks/inferred-checks/datastore-light.png
Labels: documentation

#534 QUA-375: RC2025.02.26
  docs/changelog.md
Labels: release notes

#535 QUA-370: Update"Manage Anomalies" File as per the latest release.
  docs/assets/datastores/manage-anomalies/datastore-dark-1.png
  docs/assets/datastores/manage-anomalies/datastore-light-1.png
Labels: documentation

#533 QUA-370: Update File "Export Check Templates" as per the latest release.
  docs/assets/checks/export-check-templates/enrichment-datastore-dark-6.png
  docs/assets/checks/export-check-templates/enrichment-datastore-light-6.png
  docs/assets/checks/export-check-templates/library-dark-1.png
  docs/assets/checks/export-check-templates/library-light-1.png
Labels: documentation

#536 QUA-372: Update "Enrichment Support Datastores" File.
  docs/enrichment-support/enrichment-support-datastores.md
  mkdocs.yml
Labels: documentation
