Repository Qualytics/userguide, pull requests merged in 2025-04, with the labels that each got.

#609 QUA-406: Update "Insights" file as per the latest release.
  docs/assets/explore/insights/acknowledged-anomalies-13-dark.png
  docs/assets/explore/insights/acknowledged-anomalies-13-light.png
  docs/assets/explore/insights/active-anomalies-12-dark.png
  docs/assets/explore/insights/active-anomalies-12-light.png
  docs/assets/explore/insights/anomalies-11-dark.png
  docs/assets/explore/insights/anomalies-11-light.png
  docs/assets/explore/insights/authored-dark.png
  docs/assets/explore/insights/authored-light.png
  docs/assets/explore/insights/checks-7-dark.png
  docs/assets/explore/insights/checks-7-light.png
  docs/assets/explore/insights/download-29-dark.png
  docs/assets/explore/insights/download-29-light.png
  docs/assets/explore/insights/duplicate-anomalies-15-dark.png
  docs/assets/explore/insights/duplicate-anomalies-15-light.png
  docs/assets/explore/insights/export-28-dark.png
  docs/assets/explore/insights/export-28-light.png
  docs/assets/explore/insights/failed-check-9-dark.png
  docs/assets/explore/insights/failed-check-9-light.png
  docs/assets/explore/insights/inferred-dark.png
  docs/assets/explore/insights/inferred-light.png
  docs/assets/explore/insights/insights-2-dark.png
  docs/assets/explore/insights/insights-2-light.png
  docs/assets/explore/insights/invalid-anomalies-16-dark.png
  docs/assets/explore/insights/invalid-anomalies-16-light.png
  docs/assets/explore/insights/not-asserted-10-dark.png
  docs/assets/explore/insights/not-asserted-10-light.png
  docs/assets/explore/insights/passed-check-8-dark.png
  docs/assets/explore/insights/passed-check-8-light.png
  docs/assets/explore/insights/refresh-30-dark.png
  docs/assets/explore/insights/refresh-30-light.png
  docs/assets/explore/insights/refresh-label-31-dark.png
  docs/assets/explore/insights/refresh-label-31-light.png
  docs/assets/explore/insights/resolved-anomalies-14-dark.png
  docs/assets/explore/insights/resolved-anomalies-14-light.png
  docs/assets/explore/insights/rule-type-15-dark.png
  docs/assets/explore/insights/rule-type-15-light.png
  docs/assets/explore/insights/top-16-dark.png
  docs/assets/explore/insights/top-16-light.png
  docs/explore/insights.md
Labels: documentation

#612 QUA-466: Update "Anomaly Analysis" file as per the latest release.
  docs/anomalies/anomalies.md
  docs/assets/datastores/anomalies/anomalies-action-dark.png
  docs/assets/datastores/anomalies/anomalies-action-light.png
  docs/assets/datastores/anomalies/anomalies-details-dark.png
  docs/assets/datastores/anomalies/anomalies-details-light.png
  docs/assets/datastores/anomalies/assign-tags-dark.png
  docs/assets/datastores/anomalies/assign-tags-light.png
  docs/assets/datastores/anomalies/details-dark.png
  docs/assets/datastores/anomalies/details-light.png
  docs/assets/datastores/anomalies/updated-existing-tags-dark.png
  docs/assets/datastores/anomalies/updated-existing-tags-light.png
Labels: documentation

#610 QUA-466: Update "Anomalies" file as per the latest release.
  docs/assets/explore/anomalies/ackno-dark.png
  docs/assets/explore/anomalies/ackno-light.png
  docs/assets/explore/anomalies/ackno-window-dark.png
  docs/assets/explore/anomalies/ackno-window-light.png
  docs/assets/explore/anomalies/acknowledge-dark.png
  docs/assets/explore/anomalies/acknowledge-light.png
  docs/assets/explore/anomalies/active-dark.png
  docs/assets/explore/anomalies/active-light.png
  docs/assets/explore/anomalies/all-anomalies-dark.png
  docs/assets/explore/anomalies/all-anomalies-light.png
  docs/assets/explore/anomalies/all-archived-dark.png
  docs/assets/explore/anomalies/all-archived-light.png
  docs/assets/explore/anomalies/all-dark.png
  docs/assets/explore/anomalies/all-light.png
  docs/assets/explore/anomalies/archieve-ano-dark.png
  docs/assets/explore/anomalies/archieve-ano-light.png
  docs/assets/explore/anomalies/archived-bar-dark.png
  docs/assets/explore/anomalies/archived-bar-light.png
  docs/assets/explore/anomalies/archived-dark.png
  docs/assets/explore/anomalies/archived-light.png
  docs/assets/explore/anomalies/caret-dark.png
  docs/assets/explore/anomalies/caret-light.png
  docs/assets/explore/anomalies/details-dark.png
  docs/assets/explore/anomalies/details-light.png
  docs/assets/explore/anomalies/dlt-dark.png
  docs/assets/explore/anomalies/dlt-light.png
  docs/assets/explore/anomalies/duplicate-dark.png
  docs/assets/explore/anomalies/duplicate-light.png
  docs/assets/explore/anomalies/filter-2-dark.png
  docs/assets/explore/anomalies/filter-2-light.png
  docs/assets/explore/anomalies/invalid-dark.png
  docs/assets/explore/anomalies/invalid-light.png
  docs/assets/explore/anomalies/modal-dark.png
  docs/assets/explore/anomalies/modal-light.png
  docs/assets/explore/anomalies/open-dark.png
  docs/assets/explore/anomalies/open-light.png
  docs/assets/explore/anomalies/resolved-dark.png
  docs/assets/explore/anomalies/resolved-light.png
  docs/assets/explore/anomalies/restore-button-dark.png
  docs/assets/explore/anomalies/restore-button-light.png
  docs/assets/explore/anomalies/restore-dark.png
  docs/assets/explore/anomalies/restore-light.png
  docs/assets/explore/anomalies/restored-dark.png
  docs/assets/explore/anomalies/restored-light.png
  docs/assets/explore/anomalies/select-anomalies-dark.png
  docs/assets/explore/anomalies/select-anomalies-light.png
  docs/assets/explore/anomalies/sort-dark.png
  docs/assets/explore/anomalies/sort-light.png
  docs/assets/explore/anomalies/vertical-dark.png
  docs/assets/explore/anomalies/vertical-light.png
  docs/assets/explore/anomalies/window-archive-dark.png
  docs/assets/explore/anomalies/window-archive-light.png
  docs/explore/anomalies.md
Labels: documentation

#608 QUA-466: Update "Checks" file as per the latest release.
  docs/assets/explore/checks/caret-dark.png
  docs/assets/explore/checks/caret-light.png
  docs/assets/explore/checks/sort-dark.png
  docs/assets/explore/checks/sort-light.png
  docs/explore/checks.md
Labels: documentation

#616 QUA-477: RC.2025.4.5
  docs/changelog.md
Labels: release notes

#615 QUA-475: Update "Observability" file.
  docs/assets/explore/observability/observability-metrics-dark.png
  docs/assets/explore/observability/observability-metrics-light.png
  docs/assets/explore/observability/particular-datastore-dark.png
  docs/assets/explore/observability/particular-datastore-light.png
  docs/explore/observability.md
Labels: documentation

#617 Qua475: Update "Manage Tables and Files" file.
  docs/assets/container/manage-tables-files/check-dark-14.png
  docs/assets/container/manage-tables-files/check-light-14.png
  docs/assets/container/manage-tables-files/delete-dark-25.png
  docs/assets/container/manage-tables-files/delete-light-25.png
  docs/assets/container/manage-tables-files/export-dark-23.png
  docs/assets/container/manage-tables-files/export-dark-24.png
  docs/assets/container/manage-tables-files/export-light-23.png
  docs/assets/container/manage-tables-files/export-light-24.png
  docs/assets/container/manage-tables-files/materialize-dark-24.png
  docs/assets/container/manage-tables-files/materialize-dark-30.png
  docs/assets/container/manage-tables-files/materialize-light-24.png
  docs/assets/container/manage-tables-files/materialize-light-30.png
  docs/assets/container/manage-tables-files/observability-dark-18.png
  docs/assets/container/manage-tables-files/observability-dark-19.png
  docs/assets/container/manage-tables-files/observability-light-18.png
  docs/assets/container/manage-tables-files/observability-light-19.png
  docs/assets/container/manage-tables-files/run-dark-16.png
  docs/assets/container/manage-tables-files/run-dark-17.png
  docs/assets/container/manage-tables-files/run-light-16.png
  docs/assets/container/manage-tables-files/run-light-17.png
  docs/assets/container/manage-tables-files/save-dark-21.png
  docs/assets/container/manage-tables-files/save-light-21.png
  docs/assets/container/manage-tables-files/setting-dark-4.png
  docs/assets/container/manage-tables-files/setting-dark-44.png
  docs/assets/container/manage-tables-files/setting-light-4.png
  docs/assets/container/manage-tables-files/setting-light-44.png
  docs/assets/container/manage-tables-files/tracking-dark-20.png
  docs/assets/container/manage-tables-files/tracking-light-20.png
  docs/container/manage-tables-and-files.md
Labels: documentation

#618 QUA-475: Update "Computed Fields" file.
  docs/assets/container/computed-field/caret-dark-14.png
  docs/assets/container/computed-field/caret-light-14.png
  docs/assets/container/computed-field/sort-dark-12.png
  docs/assets/container/computed-field/sort-dark-13.png
  docs/assets/container/computed-field/sort-light-12.png
  docs/assets/container/computed-field/sort-light-13.png
  docs/container/overview-of-a-computed-field.md
Labels: documentation

#622 QUA-475: Update "General" file.
  docs/assets/identifiers/general-overview/settings-dark.png
  docs/assets/identifiers/general-overview/settings-light.png
Labels: documentation

#621 QUA-475: Update "Grouping" file.
  docs/assets/identifiers/grouping-overview/settings-dark.png
  docs/assets/identifiers/grouping-overview/settings-light.png
Labels: documentation

#623 QUA-475: Update "Tokens" file.
  docs/assets/tokens/enter-values-dark-5.png
  docs/assets/tokens/enter-values-light-5.png
  docs/assets/tokens/generate-token-dark-6.png
  docs/assets/tokens/generate-token-light-6.png
  docs/assets/tokens/token-detail-dark-4.png
  docs/assets/tokens/token-detail-light-4.png
  docs/settings/tokens/overview-of-tokens.md
Labels: documentation

#626 QUA-494: Update "Datastore Settings" userguide as per the latest release.
  docs/assets/datastore-settings/decay-period-dark-19.png
  docs/assets/datastore-settings/decay-period-light-19.png
  docs/assets/datastore-settings/factor-weights-dark-20.png
  docs/assets/datastore-settings/factor-weights-light-20.png
  docs/assets/datastore-settings/score-save-dark-21.png
  docs/assets/datastore-settings/score-save-light-21.png
  docs/assets/datastore-settings/score-settings-dark-18.png
  docs/assets/datastore-settings/score-settings-light-18.png
  docs/source-datastore/datastore-settings.md
Labels: documentation

#624 QUA-475: Update "Explore Observability" file.
  docs/assets/explore/observability/field-dark.png
  docs/assets/explore/observability/field-light.png
  docs/assets/explore/observability/fields-dark.png
  docs/assets/explore/observability/fields-light.png
  docs/assets/explore/observability/freshness-dark.png
  docs/assets/explore/observability/freshness-light.png
  docs/explore/observability.md
Labels: documentation

#614 QUA-475: Update "Inferred Checks" file.
  docs/assets/checks/inferred-checks/additional-metadata-dark.png
  docs/assets/checks/inferred-checks/additional-metadata-light.png
  docs/assets/checks/inferred-checks/allow-fields-dark.png
  docs/assets/checks/inferred-checks/allow-fields-light.png
  docs/assets/checks/inferred-checks/check-actions-dark.png
  docs/assets/checks/inferred-checks/check-actions-light.png
  docs/assets/checks/inferred-checks/check-id-dark.png
  docs/assets/checks/inferred-checks/check-id-light.png
  docs/assets/checks/inferred-checks/check-summary-dark.png
  docs/assets/checks/inferred-checks/check-summary-light.png
  docs/assets/checks/inferred-checks/check-type-dark.png
  docs/assets/checks/inferred-checks/check-type-light.png
  docs/assets/checks/inferred-checks/confirm-button-dark.png
  docs/assets/checks/inferred-checks/confirm-button-light.png
  docs/assets/checks/inferred-checks/description-dark.png
  docs/assets/checks/inferred-checks/description-light.png
  docs/assets/checks/inferred-checks/fields-dark.png
  docs/assets/checks/inferred-checks/fields-light.png
  docs/assets/checks/inferred-checks/open-details-dark.png
  docs/assets/checks/inferred-checks/open-details-light.png
  docs/assets/checks/inferred-checks/successfully-updated-dark.png
  docs/assets/checks/inferred-checks/successfully-updated-light.png
  docs/assets/checks/inferred-checks/tags-dark.png
  docs/assets/checks/inferred-checks/tags-light.png
  docs/assets/checks/inferred-checks/target-dark.png
  docs/assets/checks/inferred-checks/target-light.png
  docs/assets/checks/inferred-checks/update-button-dark.png
  docs/assets/checks/inferred-checks/update-button-light.png
  docs/assets/checks/inferred-checks/validate-button-dark.png
  docs/assets/checks/inferred-checks/validate-button-light.png
  docs/assets/checks/inferred-checks/validation-successful-dark.png
  docs/assets/checks/inferred-checks/validation-successful-light.png
  docs/assets/checks/inferred-checks/warnings-dark.png
  docs/assets/checks/inferred-checks/warnings-light.png
  docs/checks/inferred-check.md
Labels: documentation

#629 QUA-504: RC.2025.4.11
  docs/changelog.md
Labels: release notes

#630 QUA-475: Update "Materialize Operation" file.
  docs/assets/container/materialize-operation/operation-scheduled-dark.png
  docs/assets/container/materialize-operation/operation-scheduled-light.png
  docs/assets/container/materialize-operation/operation-triggered-dark.png
  docs/assets/container/materialize-operation/operation-triggered-light.png
  docs/container/materialize-operation.md
Labels: documentation

#631 Qua475: Update "Export Operation" file.
  docs/container/export-operation.md
Labels: documentation

#632 QUA-475: Update "Catalog Operation" file.
  docs/assets/catalog-operations/completed-catalog-dark.png
  docs/assets/catalog-operations/completed-catalog-light.png
  docs/assets/catalog-operations/operation-scheduled-dark.png
  docs/assets/catalog-operations/operation-scheduled-light.png
  docs/assets/catalog-operations/operation-triggered-dark.png
  docs/assets/catalog-operations/operation-triggered-light.png
  docs/source-datastore/catalog.md
Labels: documentation

#635 QUA-507: Update "Checks" userguide as per the latest release.
  docs/assets/explore/checks/filter2-dark.png
  docs/assets/explore/checks/filter2-light.png
  docs/explore/checks.md
Labels: documentation

#628 QUA-475: Update "Enrichment Datastore Overview" file.
  docs/enrichment/overview-of-an-enrichment-datastore.md
Labels: documentation

#634 QUA-507: Update "Anomalies" userguide as per the latest release.
  docs/assets/explore/anomalies/filter-2-dark.png
  docs/assets/explore/anomalies/filter-2-light.png
  docs/explore/anomalies.md
Labels: documentation

#638 QUA-507: Update "Connections" userguide as per the latest release.
  docs/assets/connections/confirm-delete-dark-9.png
  docs/assets/connections/confirm-delete-light-9.png
  docs/assets/connections/connection-details-dark-4.png
  docs/assets/connections/connection-details-light-4.png
  docs/assets/connections/connection-updated-dark-6.png
  docs/assets/connections/connection-updated-light-6.png
  docs/assets/connections/connections-dark-2.png
  docs/assets/connections/connections-light-2.png
  docs/assets/connections/delete-window-dark-8.png
  docs/assets/connections/delete-window-light-8.png
  docs/assets/connections/filter-dark-14.png
  docs/assets/connections/filter-light-14.png
  docs/assets/connections/save-connection-dark-5.png
  docs/assets/connections/save-connection-light-5.png
  docs/assets/connections/sort-connection-dark-13.png
  docs/assets/connections/sort-connection-light-13.png
  docs/assets/connections/view-connections-dark-12.png
  docs/assets/connections/view-connections-light-12.png
  docs/settings/connections/manage-connections.md
Labels: documentation

#636 QUA-507: Update "Manage Anomalies" userguide as per the latest release.
  docs/anomalies/manage-anomalies.md
  docs/assets/datastores/manage-anomalies/arrange-dark.png
  docs/assets/datastores/manage-anomalies/arrange-light.png
  docs/assets/datastores/manage-anomalies/filter-dark.png
  docs/assets/datastores/manage-anomalies/filter-light.png
  docs/assets/datastores/manage-anomalies/sort-dark.png
  docs/assets/datastores/manage-anomalies/sort-light.png
Labels: documentation

#641 QUA-507: Update "Manage Checks" userguide as per the latest release.
  docs/assets/checks/manage-checks/arrange-dark.png
  docs/assets/checks/manage-checks/arrange-light.png
  docs/assets/checks/manage-checks/filter-dark.png
  docs/assets/checks/manage-checks/filter-light.png
  docs/assets/checks/manage-checks/sort-dark.png
  docs/assets/checks/manage-checks/sort-light.png
  docs/checks/manage-checks.md
Labels: documentation

#643 QUA-507: Update "Web Application" userguide as per the latest release.
  docs/assets/dashboard/global-settings-dark.png
  docs/assets/dashboard/global-settings-light.png
  docs/web-app.md
Labels: enhancement

#642 QUA-507: Update"Tokens" Document as per the latest release.
  docs/assets/tokens/enter-values-dark-5.png
  docs/assets/tokens/enter-values-light-5.png
  docs/assets/tokens/generate-token-dark-3.png
  docs/assets/tokens/generate-token-dark-6.png
  docs/assets/tokens/generate-token-light-3.png
  docs/assets/tokens/generate-token-light-6.png
  docs/assets/tokens/revoked-sucessfully-dark-9.png
  docs/assets/tokens/revoked-sucessfully-light-9.png
  docs/assets/tokens/token-detail-dark-4.png
  docs/assets/tokens/token-detail-light-4.png
  docs/assets/tokens/tokens-dark-2.png
  docs/assets/tokens/tokens-light-2.png
Labels: documentation

#644 QUA-524: RC.2025.4.24
  docs/changelog.md
Labels: release notes

#646 QUA-475: Update "Tags" file.
  docs/assets/tags/tag-created-dark.png
  docs/assets/tags/tag-created-light.png
  docs/assets/tags/tag-deleted-dark-13.png
  docs/assets/tags/tag-deleted-light-13.png
  docs/assets/tags/tag-updated-dark.png
  docs/assets/tags/tag-updated-light.png
  docs/tags/overview-of-tag.md
Labels: documentation

#649 QUA-507: Update "Quick Start Guide" userguide as per the latest release.
  docs/assets/quick-start-guide/explore-activity-dark.png
  docs/assets/quick-start-guide/explore-activity-light.png
  docs/assets/quick-start-guide/explore-insights-dark.png
  docs/assets/quick-start-guide/explore-insights-light.png
  docs/assets/quick-start-guide/explore-profiles-dark.png
  docs/assets/quick-start-guide/explore-profiles-light.png
  docs/assets/quick-start-guide/flows-dark.png
  docs/assets/quick-start-guide/flows-light.png
  docs/assets/quick-start-guide/observability-dark.png
  docs/assets/quick-start-guide/observability-light.png
  docs/assets/quick-start-guide/settings-connections-dark.png
  docs/assets/quick-start-guide/settings-connections-light.png
  docs/assets/quick-start-guide/settings-integrations-dark.png
  docs/assets/quick-start-guide/settings-integrations-light.png
  docs/assets/quick-start-guide/settings-security-dark.png
  docs/assets/quick-start-guide/settings-security-light.png
  docs/assets/quick-start-guide/settings-status-dark.png
  docs/assets/quick-start-guide/settings-status-light.png
  docs/assets/quick-start-guide/settings-tags-dark.png
  docs/assets/quick-start-guide/settings-tags-light.png
  docs/quick-start-guide.md
Labels: documentation

#648 QUA-475: Update "Datastore Settings" file.
  docs/assets/datastore-settings/datastore-unfavorited-dark.png
  docs/assets/datastore-settings/datastore-unfavorited-light.png
  docs/source-datastore/datastore-settings.md
Labels: documentation

#647 QUA-475: Update "Containers Overview" file.
  docs/assets/container/containers/settings-dark.png
  docs/assets/container/containers/settings-light.png
  docs/container/container.md
Labels: documentation

#651 QUA-534: Update "Manage Checks in Datastore" file as per the latest release.
  docs/assets/checks/manage-checks/filter-dark.png
  docs/assets/checks/manage-checks/filter-light.png
  docs/assets/checks/manage-checks/filters-dark.png
  docs/assets/checks/manage-checks/filters-light.png
  docs/checks/manage-checks.md
Labels: documentation

#650 QUA-534: Update"Computed Fields" userguide as per the latest release.
  docs/assets/container/computed-field/filter-dark-15.png
  docs/assets/container/computed-field/filter-light-15.png
  docs/container/overview-of-a-computed-field.md
Labels: documentation

#652 QUA-534: Update "Manage Anomalies" userguide as per the latest release.
  docs/anomalies/manage-anomalies.md
  docs/assets/datastores/manage-anomalies/filter-dark.png
  docs/assets/datastores/manage-anomalies/filter-light.png
  docs/assets/datastores/manage-anomalies/filters-dark.png
  docs/assets/datastores/manage-anomalies/filters-light.png
Labels: documentation

#653 QUA-534: Update "Scan Operation" file as per the latest release.
  docs/assets/datastores/scan/all-operation-dark.png
  docs/assets/datastores/scan/all-operation-light.png
  docs/assets/datastores/scan/anomaly-option-dark.png
  docs/assets/datastores/scan/anomaly-option-light.png
  docs/assets/datastores/scan/anomalyy-dark.png
  docs/assets/datastores/scan/anomalyy-light.png
  docs/assets/datastores/scan/click-schedule-dark.png
  docs/assets/datastores/scan/click-schedule-light.png
  docs/assets/datastores/scan/incremental-dark.png
  docs/assets/datastores/scan/incremental-light.png
  docs/assets/datastores/scan/next-button-dark.png
  docs/assets/datastores/scan/next-button-light.png
  docs/assets/datastores/scan/next-dark.png
  docs/assets/datastores/scan/next-light.png
  docs/assets/datastores/scan/nextt-dark.png
  docs/assets/datastores/scan/nextt-light.png
  docs/assets/datastores/scan/record-limit-line-dark.png
  docs/assets/datastores/scan/record-limit-line-light.png
  docs/assets/datastores/scan/run-now-dark.png
  docs/assets/datastores/scan/run-now-light.png
  docs/assets/datastores/scan/select-check-dark.png
  docs/assets/datastores/scan/select-check-light.png
  docs/assets/datastores/scan/source-record-limit-dark.png
  docs/assets/datastores/scan/source-record-limit-light.png
  docs/assets/datastores/scan/specfic-dark.png
  docs/assets/datastores/scan/specfic-light.png
  docs/assets/datastores/scan/starting-threshold-dark.png
  docs/assets/datastores/scan/starting-threshold-light.png
  docs/assets/datastores/scan/tag-dark.png
  docs/assets/datastores/scan/tag-light.png
  docs/enrichment-support/supported-enrichment-datastores.md
  docs/source-datastore/scan.md
  mkdocs.yml
Labels: documentation
