Repository Qualytics/userguide, pull requests merged in 2025-07, with the labels that each got.

#742 QUA-627: Update "Export Check Templates" userguide as per the latest release.
  docs/assets/checks/export-check-templates/download-templates-dark-8.png
  docs/assets/checks/export-check-templates/download-templates-light-8.png
  docs/assets/checks/export-check-templates/enrichment-datastore-dark-6.png
  docs/assets/checks/export-check-templates/enrichment-datastore-light-6.png
  docs/assets/checks/export-check-templates/exported-templates-dark-7.png
  docs/assets/checks/export-check-templates/exported-templates-light-7.png
  docs/checks/export-check-templates.md
Labels: documentation

#741 QUA-627: Update "External Scan" userguide as per the latest release.
  docs/assets/external-scan/container-dark-3.png
  docs/assets/external-scan/container-light-3.png
  docs/assets/external-scan/datastore-dark-1.png
  docs/assets/external-scan/datastore-light-1.png
  docs/assets/external-scan/external-scan-dark-4.png
  docs/assets/external-scan/external-scan-light-4.png
  docs/assets/external-scan/tables-dark-2.png
  docs/assets/external-scan/tables-light-2.png
  docs/source-datastore/external-scan.md
Labels: documentation

#748 QUA-688: Remove some pages that should not appear in search
  docs/components/anomaly-support/index.md
  docs/components/comparators/duration.md
  docs/components/comparators/index.md
  docs/components/comparators/numeric.md
  docs/components/comparators/string.md
  docs/components/general-props/filter-guide.md
  docs/components/general-props/index.md
Labels: bug

#752 Chore: update plugin versions
  mkdocs.yml
  requirements.txt
Labels: dependencies

#743 QUA-605: Fix typos in "Observability" userguide.
  docs/observability/observability.md
Labels: documentation

#756 QUA-693: Update "Computed Tables and Files" userguide as per the latest release.
  docs/assets/datastores/add-computed-tables-files/add-compute-file-dark.png
  docs/assets/datastores/add-computed-tables-files/add-compute-file-light.png
  docs/assets/datastores/add-computed-tables-files/add-computed-table-dark.png
  docs/assets/datastores/add-computed-tables-files/add-computed-table-light.png
  docs/assets/datastores/add-computed-tables-files/click-add-dark.png
  docs/assets/datastores/add-computed-tables-files/click-add-file-dark.png
  docs/assets/datastores/add-computed-tables-files/click-add-file-light.png
  docs/assets/datastores/add-computed-tables-files/click-add-light.png
  docs/assets/datastores/add-computed-tables-files/select-datastore-dark.png
  docs/assets/datastores/add-computed-tables-files/select-datastore-light.png
  docs/container/computed-tables-and-files.md
Labels: documentation

#755 QUA-693: Update "Checks in Datastore" userguide as per the latest release.
  docs/assets/datastore-checks/checks-datastore/activity-dark-98.png
  docs/assets/datastore-checks/checks-datastore/activity-light-98.png
  docs/assets/datastore-checks/checks-datastore/check-version-dark.png
  docs/assets/datastore-checks/checks-datastore/check-version-light.png
  docs/assets/datastore-checks/checks-datastore/right-panel-dark.png
  docs/assets/datastore-checks/checks-datastore/right-panel-light.png
  docs/assets/datastore-checks/checks-datastore/version-dark.png
  docs/assets/datastore-checks/checks-datastore/version-light.png
  docs/datastore-checks/checks-datastore.md
Labels: documentation

#754 QUA-627: Update "Containers Data Preview" userguide as per the latest release.
  docs/assets/container/data-preview/download-dark.png
  docs/assets/container/data-preview/download-light.png
  docs/assets/container/data-preview/field-dark.png
  docs/assets/container/data-preview/field-light.png
  docs/assets/container/data-preview/filter-dark.png
  docs/assets/container/data-preview/filter-light.png
  docs/assets/container/data-preview/list-dark.png
  docs/assets/container/data-preview/list-light.png
  docs/assets/container/data-preview/preview-dark.png
  docs/assets/container/data-preview/preview-light.png
  docs/assets/container/data-preview/refresh-dark.png
  docs/assets/container/data-preview/refresh-light.png
  docs/assets/container/data-preview/select-dark.png
  docs/assets/container/data-preview/select-light.png
  docs/assets/container/data-preview/table-dark.png
  docs/assets/container/data-preview/table-light.png
  docs/assets/container/data-preview/tabular-dark.png
  docs/assets/container/data-preview/tabular-light.png
  docs/container/data-preview.md
Labels: documentation

#753 QUA-627: Update "Data Preview" userguide as per the latest release.
  docs/assets/enrichment/data-preview/all-dark.png
  docs/assets/enrichment/data-preview/all-light.png
  docs/assets/enrichment/data-preview/click-dark.png
  docs/assets/enrichment/data-preview/click-light.png
  docs/assets/enrichment/data-preview/data-dark.png
  docs/assets/enrichment/data-preview/data-light.png
  docs/assets/enrichment/data-preview/data-preview-dark.png
  docs/assets/enrichment/data-preview/data-preview-light.png
  docs/assets/enrichment/data-preview/data1-dark.png
  docs/assets/enrichment/data-preview/data1-light.png
  docs/assets/enrichment/data-preview/data2-dark.png
  docs/assets/enrichment/data-preview/data2-light.png
  docs/assets/enrichment/data-preview/data3-dark.png
  docs/assets/enrichment/data-preview/data3-light.png
  docs/assets/enrichment/data-preview/data4-dark.png
  docs/assets/enrichment/data-preview/data4-light.png
  docs/assets/enrichment/data-preview/data5-dark.png
  docs/assets/enrichment/data-preview/data5-light.png
  docs/assets/enrichment/data-preview/enrichment-dark.png
  docs/assets/enrichment/data-preview/enrichment-light.png
  docs/assets/enrichment/data-preview/export-dark.png
  docs/assets/enrichment/data-preview/export-light.png
  docs/assets/enrichment/data-preview/filter-dark.png
  docs/assets/enrichment/data-preview/filter-light.png
  docs/assets/enrichment/data-preview/materialize-dark.png
  docs/assets/enrichment/data-preview/materialize-light.png
  docs/assets/enrichment/data-preview/preview-dark.png
  docs/assets/enrichment/data-preview/preview-light.png
  docs/assets/enrichment/data-preview/refresh-dark.png
  docs/assets/enrichment/data-preview/refresh-light.png
  docs/assets/enrichment/data-preview/remediation-dark.png
  docs/assets/enrichment/data-preview/remediation-light.png
  docs/assets/enrichment/data-preview/specific2-dark.png
  docs/assets/enrichment/data-preview/specific2-light.png
  docs/assets/enrichment/data-preview/unlinked-dark.png
  docs/assets/enrichment/data-preview/unlinked-light.png
  docs/enrichment/enrichment-datastore-preview.md
Labels: documentation

#761 QUA-693: Update "Authored Check" userguide as per the latest release.
  docs/assets/checks/authored-checks/add-btn-dark.png
  docs/assets/checks/authored-checks/add-btn-light.png
  docs/assets/checks/authored-checks/checks-tab-dark.png
  docs/assets/checks/authored-checks/checks-tab-light.png
  docs/assets/checks/authored-checks/confirm-dark.png
  docs/assets/checks/authored-checks/confirm-light.png
  docs/assets/checks/authored-checks/coverage-dark.png
  docs/assets/checks/authored-checks/coverage-light.png
  docs/assets/checks/authored-checks/datastore-dark.png
  docs/assets/checks/authored-checks/datastore-light.png
  docs/assets/checks/authored-checks/date-dark.png
  docs/assets/checks/authored-checks/date-light.png
  docs/assets/checks/authored-checks/description-dark.png
  docs/assets/checks/authored-checks/description-light.png
  docs/assets/checks/authored-checks/field-dark.png
  docs/assets/checks/authored-checks/field-light.png
  docs/assets/checks/authored-checks/file-dark.png
  docs/assets/checks/authored-checks/file-light.png
  docs/assets/checks/authored-checks/filter-clause-dark.png
  docs/assets/checks/authored-checks/filter-clause-light.png
  docs/assets/checks/authored-checks/metadata-dark.png
  docs/assets/checks/authored-checks/metadata-light.png
  docs/assets/checks/authored-checks/tag-dark.png
  docs/assets/checks/authored-checks/tag-light.png
  docs/checks/authored-check.md
Labels: documentation

#773 QUA-724: v2025.7.18
  docs/changelog.md
Labels: release notes

#768 QUA-627: Update "Inferred Check" userguide as per the latest release.
  docs/assets/checks/inferred-checks/additional-metadata-dark.png
  docs/assets/checks/inferred-checks/additional-metadata-light.png
  docs/assets/checks/inferred-checks/allow-fields-dark.png
  docs/assets/checks/inferred-checks/allow-fields-light.png
  docs/assets/checks/inferred-checks/check-actions-dark.png
  docs/assets/checks/inferred-checks/check-actions-light.png
  docs/assets/checks/inferred-checks/check-id-dark.png
  docs/assets/checks/inferred-checks/check-id-light.png
  docs/assets/checks/inferred-checks/check-summary-dark.png
  docs/assets/checks/inferred-checks/check-summary-light.png
  docs/assets/checks/inferred-checks/check-type-dark.png
  docs/assets/checks/inferred-checks/check-type-light.png
  docs/assets/checks/inferred-checks/checks-dark.png
  docs/assets/checks/inferred-checks/checks-light.png
  docs/assets/checks/inferred-checks/confirm-button-dark.png
  docs/assets/checks/inferred-checks/confirm-button-light.png
  docs/assets/checks/inferred-checks/datastore-dark.png
  docs/assets/checks/inferred-checks/datastore-light.png
  docs/assets/checks/inferred-checks/description-dark.png
  docs/assets/checks/inferred-checks/description-light.png
  docs/assets/checks/inferred-checks/fields-dark.png
  docs/assets/checks/inferred-checks/fields-light.png
  docs/assets/checks/inferred-checks/open-details-dark.png
  docs/assets/checks/inferred-checks/open-details-light.png
  docs/assets/checks/inferred-checks/profiling-dark.png
  docs/assets/checks/inferred-checks/profiling-light.png
  docs/assets/checks/inferred-checks/run-dark.png
  docs/assets/checks/inferred-checks/run-light.png
  docs/assets/checks/inferred-checks/tags-dark.png
  docs/assets/checks/inferred-checks/tags-light.png
  docs/assets/checks/inferred-checks/target-dark.png
  docs/assets/checks/inferred-checks/target-light.png
  docs/assets/checks/inferred-checks/warnings-dark.png
  docs/assets/checks/inferred-checks/warnings-light.png
  docs/checks/inferred-check.md
Labels: documentation

#772 QUA-725: Fix the warnings in userguide.
  docs/assets/datastore-checks/manage-checks/archived-btn-dark-66.png
  docs/assets/datastore-checks/manage-checks/archived-btn-light-66.png
  docs/datastore-checks/manage-checks.md
  docs/glossary.md
  docs/integrations/alerting.md
Labels: documentation

#779 QUA-753: Block not allowed users from merge the PR
  .github/CODEOWNERS
Labels: enhancement

#787 QUA-770: v2025.7.28
  docs/changelog.md
Labels: release notes
