Repository Qualytics/userguide, pull requests merged in 2025-03, with the labels that each got.

#538 QUA-380: Update "Scan Operation" File as per the latest release.
  docs/assets/datastores/scan/anomaly-option-dark.png
  docs/assets/datastores/scan/anomaly-option-light.png
  docs/assets/datastores/scan/next-buttonn-dark.png
  docs/assets/datastores/scan/next-buttonn-light.png
  docs/assets/datastores/scan/scan-settings-dark.png
  docs/assets/datastores/scan/scan-settings-light.png
  docs/source-datastore/scan.md
Labels: documentation

#539 QUA-389: Add "Export Operation" file as per the latest release.
  docs/assets/container/export-operation/assest-dark.png
  docs/assets/container/export-operation/assest-light.png
  docs/assets/container/export-operation/export-dark.png
  docs/assets/container/export-operation/export-light.png
  docs/assets/container/export-operation/msg-dark.png
  docs/assets/container/export-operation/msg-light.png
  docs/assets/container/export-operation/operation-dark.png
  docs/assets/container/export-operation/operation-light.png
  docs/assets/container/export-operation/profile-dark.png
  docs/assets/container/export-operation/profile-light.png
  docs/assets/container/export-operation/profile2-dark.png
  docs/assets/container/export-operation/profile2-light.png
  docs/assets/container/export-operation/review-dark.png
  docs/assets/container/export-operation/review-light.png
  docs/assets/container/export-operation/select-dark.png
  docs/assets/container/export-operation/select-light.png
  docs/assets/container/export-operation/snow-dark.png
  docs/assets/container/export-operation/snow-light.png
  docs/assets/container/export-operation/visible-dark.png
  docs/assets/container/export-operation/visible-light.png
  docs/container/export-operation.md
  mkdocs.yml
Labels: documentation

#540 QUA-389: Create "Materialize Operation" File as per the latest release.
  docs/assets/container/materialize-operation/data-dark.png
  docs/assets/container/materialize-operation/data-light.png
  docs/assets/container/materialize-operation/datastore-dark.png
  docs/assets/container/materialize-operation/datastore-light.png
  docs/assets/container/materialize-operation/material-dark.png
  docs/assets/container/materialize-operation/material-light.png
  docs/assets/container/materialize-operation/name-dark.png
  docs/assets/container/materialize-operation/name-light.png
  docs/assets/container/materialize-operation/next-dark.png
  docs/assets/container/materialize-operation/next-light.png
  docs/assets/container/materialize-operation/preview-dark.png
  docs/assets/container/materialize-operation/preview-light.png
  docs/assets/container/materialize-operation/preview2-dark.png
  docs/assets/container/materialize-operation/preview2-light.png
  docs/assets/container/materialize-operation/record-dark.png
  docs/assets/container/materialize-operation/record-light.png
  docs/assets/container/materialize-operation/run-dark.png
  docs/assets/container/materialize-operation/run-light.png
  docs/assets/container/materialize-operation/schedule-dark.png
  docs/assets/container/materialize-operation/schedule-light.png
  docs/assets/container/materialize-operation/schedule2-dark.png
  docs/assets/container/materialize-operation/schedule2-light.png
  docs/assets/container/materialize-operation/select-dark.png
  docs/assets/container/materialize-operation/select-light.png
  docs/assets/container/materialize-operation/time-dark.png
  docs/assets/container/materialize-operation/time-light.png
  docs/assets/container/materialize-operation/window-dark.png
  docs/assets/container/materialize-operation/window-light.png
  docs/container/materialize-operation.md
  mkdocs.yml
Labels: documentation

#541 QUA-370:Update "Datastore Settings" file as per the latest release.
  docs/assets/datastore-settings/teams-dark-1.png
  docs/assets/datastore-settings/teams-light-1.png
Labels: documentation

#542 QUA-370: Update "Export check templates" file as per the release
  docs/assets/checks/export-check-templates/download-templates-dark-8.png
  docs/assets/checks/export-check-templates/download-templates-light-8.png
  docs/assets/checks/export-check-templates/exported-templates-dark-7.png
  docs/assets/checks/export-check-templates/exported-templates-light-7.png
Labels: documentation

#545 QUA-402 RC.2025.03.05
  docs/changelog.md
Labels: release notes

#548 QUA-401: Update "Computed tables and files" userguide.
  docs/assets/datastores/add-computed-tables-files/select-datastore-dark.png
  docs/assets/datastores/add-computed-tables-files/select-datastore-light.png
Labels: documentation

#550 QUA-401: Updated "Anomalies"userguide.
  docs/assets/explore/anomalies/explore-dark.png
  docs/assets/explore/anomalies/explore-light.png
Labels: documentation

#549 QUA-401: Updated "Activity" userguide.
  docs/assets/explore/activity/explore-dark.png
  docs/assets/explore/activity/explore-light.png
Labels: documentation

#553 QUA-401: Update "Checks overview" file.
  docs/assets/checks/checks-overview/datastores-dark-1.png
  docs/assets/checks/checks-overview/datastores-light-1.png
  docs/assets/checks/checks-overview/explore-dark-5.png
  docs/assets/checks/checks-overview/explore-light-5.png
Labels: documentation

#552 QUA-401: Update "General overview" file.
  docs/assets/identifiers/general-overview/datastore-dark.png
  docs/assets/identifiers/general-overview/datastore-light.png
Labels: documentation

#554 Fix: misspelling word
  docs/changelog.md
Labels: bug, release notes

#555 Qua401:Update "Data Preview" file.
  docs/assets/container/data-preview/alter-dark.png
  docs/assets/container/data-preview/alter-light.png
  docs/assets/container/data-preview/select-dark.png
  docs/assets/container/data-preview/select-light.png
  docs/changelog.md
Labels: documentation

#561 QUA-401: Update "Profile Operations" file.
  docs/assets/profile-operations/adding-source-datastore-dark.png
  docs/assets/profile-operations/adding-source-datastore-light.png
Labels: bug, documentation

#559 QUA-401: Update "Right Click Options" file.
  docs/assets/right-click/source-dark-1.png
  docs/assets/right-click/source-dark-2.png
  docs/assets/right-click/source-light-1.png
  docs/assets/right-click/source-light-2.png
  docs/assets/right-click/tables-files-dark-3.png
  docs/assets/right-click/tables-files-light-3.png
Labels: bug, documentation

#558 QUA-401: Update "Computed Fields" file.
  docs/assets/container/computed-field/datastore-dark-1.png
  docs/assets/container/computed-field/datastore-light-1.png
  docs/assets/container/computed-field/explore-dark.png
  docs/assets/container/computed-field/explore-light.png
  docs/assets/container/computed-field/team-dark.png
  docs/assets/container/computed-field/team-light.png
Labels: bug, documentation

#557 QUA-401: Update "Manage tables and files" file.
  docs/assets/container/manage-tables-files/select-dark-1.png
  docs/assets/container/manage-tables-files/select-light-1.png
Labels: bug, documentation

#562 QUA-401: Update "Checks" file.
  docs/assets/explore/checks/explore-dark.png
  docs/assets/explore/checks/explore-light.png
Labels: documentation

#563 QUA-401: Update "Profiles" file.
  docs/assets/explore/profiles/explore-dark.png
  docs/assets/explore/profiles/explore-light.png
Labels: documentation

#565 QUA-401: Update "Health" file.
  docs/assets/health/global-settings-dark-1.png
  docs/assets/health/global-settings-light-1.png
Labels: bug, documentation

#567 QUA-412: Update "Observability" File .
  docs/observability/observability.md
Labels: documentation

#568 QUA-401: Update "Freshness Check" file.
  docs/assets/checks/freshness-check/select-dark.png
  docs/assets/checks/freshness-check/select-light.png
Labels: bug, documentation

#570 QUA-401: Update "Connections" file.
  docs/assets/connections/global-setting-dark-1.png
  docs/assets/connections/global-setting-light-1.png
Labels: bug, documentation

#571 QUA-401: Update "Insights" file.
  docs/assets/explore/insights/explore-1-dark.png
  docs/assets/explore/insights/explore-1-light.png
Labels: bug, documentation

#572 QUA-401: Update "Enrichment Datastore Overview" file.
  docs/assets/enrichment/overview-enrichment/click-dark.png
  docs/assets/enrichment/overview-enrichment/click-light.png
Labels: bug, documentation

#573 QUA-401: Update "Add Enrichment Datastore" file.
  docs/assets/enrichment/add-enrichment/enrichment-dark.png
  docs/assets/enrichment/add-enrichment/enrichment-light.png
Labels: bug, documentation

#582 QUA-422 RC.2025.03.17
  docs/changelog.md
Labels: release notes

#576 QUA-401: Update "Data Preview" file.
  docs/assets/enrichment/data-preview/click-dark.png
  docs/assets/enrichment/data-preview/click-light.png
Labels: documentation

#577 QUA-401: Update "Datastore Settings" file.
  docs/assets/datastore-settings/add-datastore-dark-1.png
  docs/assets/datastore-settings/add-datastore-light-1.png
Labels: bug, documentation

#578 QUA-401: Update "External Scan" file.
  docs/assets/external-scan/datastore-dark-1.png
  docs/assets/external-scan/datastore-light-1.png
Labels: bug, documentation

#580 QUA-401: Update "Catalog Operations" file.
  docs/assets/catalog-operations/add-source-datastore-dark.png
  docs/assets/catalog-operations/add-source-datastore-light.png
Labels: bug, documentation

#581 QUA-401: Update "Assign Tags" file.
  docs/assets/assign-tags/add-datastore-dark-1.png
  docs/assets/assign-tags/add-datastore-light-1.png
Labels: documentation

#583 QUA-401: Update "Link Datastore" file.
  docs/assets/enrichment/link-datastore/datastore-dark.png
  docs/assets/enrichment/link-datastore/datastore-light.png
Labels: bug, documentation

#584 QUA-401: Update "Data Source" file.
  docs/assets/datastores/what-is/home-dark-4.png
  docs/assets/datastores/what-is/home-dark-5.png
  docs/assets/datastores/what-is/home-light-4.png
  docs/assets/datastores/what-is/home-light-5.png
Labels: bug, documentation

#574 Fix: Observability measurement chart
  docs/observability/observability.md
Labels: bug

#585 Qua401:Update "Web Application" file.
  docs/assets/dashboard/global-search-dark.png
  docs/assets/dashboard/global-search-light.png
  docs/assets/dashboard/source-datastore-nav-dark.png
  docs/assets/dashboard/source-datastore-nav-light.png
Labels: documentation

#586 QUA-401: Update "Presto" file.
  docs/assets/datastores/presto/connector-dark-3.png
  docs/assets/datastores/presto/connector-light-3.png
  docs/assets/datastores/presto/detail-dark-13.png
  docs/assets/datastores/presto/detail-dark-7.png
  docs/assets/datastores/presto/detail-light-13.png
  docs/assets/datastores/presto/detail-light-7.png
Labels: bug, documentation

#588 QUA-401: Update "Trino" file.
  docs/assets/datastores/trino/existing-dark.png
  docs/assets/datastores/trino/existing-light.png
  docs/assets/datastores/trino/form-dark.png
  docs/assets/datastores/trino/form-light.png
  docs/assets/datastores/trino/secret-dark.png
  docs/assets/datastores/trino/secret-light.png
  docs/assets/datastores/trino/select-dark.png
  docs/assets/datastores/trino/select-light.png
  docs/assets/datastores/trino/selectedd-dark.png
  docs/assets/datastores/trino/selectedd-light.png
Labels: bug, documentation

#589 QUA-436: Update "Export Operation" File
  docs/assets/container/export-operation/assest-dark.png
  docs/assets/container/export-operation/assest-light.png
  docs/assets/container/export-operation/name-dark-1.png
  docs/assets/container/export-operation/name-light-1.png
  docs/assets/container/export-operation/operation-dark.png
  docs/assets/container/export-operation/operation-light.png
  docs/assets/container/export-operation/operation-scheduled-dark.png
  docs/assets/container/export-operation/operation-scheduled-light.png
  docs/assets/container/export-operation/profile2-dark.png
  docs/assets/container/export-operation/profile2-light.png
  docs/assets/container/export-operation/schedule-dark-1.png
  docs/assets/container/export-operation/schedule-dark.png
  docs/assets/container/export-operation/schedule-light-1.png
  docs/assets/container/export-operation/schedule-light.png
  docs/assets/container/export-operation/time-dark-1.png
  docs/assets/container/export-operation/time-light-1.png
  docs/container/export-operation.md
  mkdocs.yml
Labels: bug, documentation

#590 QUA-436: Update "Scan Operation" File.
  docs/assets/datastores/scan/aborted-operation-dark.png
  docs/assets/datastores/scan/aborted-operation-light.png
  docs/assets/datastores/scan/anomaly-option-dark.png
  docs/assets/datastores/scan/anomaly-option-light.png
  docs/assets/datastores/scan/next-buttonn-dark.png
  docs/assets/datastores/scan/next-buttonn-light.png
  docs/assets/datastores/scan/records-scan-operation-dark.png
  docs/assets/datastores/scan/records-scan-operation-light.png
  docs/assets/datastores/scan/result-scan-operation-dark.png
  docs/assets/datastores/scan/result-scan-operation-light.png
  docs/assets/datastores/scan/running-dark.png
  docs/assets/datastores/scan/running-light.png
  docs/assets/datastores/scan/scan-settings-dark.png
  docs/assets/datastores/scan/scan-settings-light.png
  docs/assets/datastores/scan/success-2-dark.png
  docs/assets/datastores/scan/success-2-light.png
  docs/assets/datastores/scan/warning-dark.png
  docs/assets/datastores/scan/warning-light.png
  docs/source-datastore/scan.md
Labels: documentation

#594 QUA-442: RC.2025.03.23
  docs/changelog.md
Labels: release notes

#591 Qua401:Update "Observability" file.
  docs/assets/observability/source-dark-1.png
  docs/assets/observability/source-light-1.png
Labels: documentation

#595 QUA-370: Update "Computed Tables and Files" file.
  docs/changelog.md
  docs/container/computed-tables-and-files.md
Labels: bug, documentation

#592 QUA-401: Update "MariaDB" file.
  docs/assets/datastores/maria-db/connections-dark.png
  docs/assets/datastores/maria-db/connections-light.png
  docs/assets/datastores/maria-db/connector-dark.png
  docs/assets/datastores/maria-db/connector-light.png
  docs/assets/datastores/maria-db/details-dark.png
  docs/assets/datastores/maria-db/details-light.png
  docs/assets/datastores/maria-db/form-dark.png
  docs/assets/datastores/maria-db/form-light.png
  docs/assets/datastores/maria-db/secret-dark.png
  docs/assets/datastores/maria-db/secret-light.png
Labels: bug, documentation

#593 Qua401:Update "Synapse" file.
  docs/assets/datastores/synapse/credential-dark.png
  docs/assets/datastores/synapse/credential-light.png
  docs/assets/datastores/synapse/enrichment-datastore-connector-dark.png
  docs/assets/datastores/synapse/enrichment-datastore-connector-light.png
  docs/assets/datastores/synapse/existing-credentials-dark.png
  docs/assets/datastores/synapse/existing-credentials-light.png
  docs/assets/datastores/synapse/secret-management-dark.png
  docs/assets/datastores/synapse/secret-management-light.png
  docs/assets/datastores/synapse/synapse-connector-dark.png
  docs/assets/datastores/synapse/synapse-connector-light.png
Labels: documentation

#596 QUA-370: Update "External Tag Propagation" file.
  docs/settings/catalog-integrations/external-tag-propagation.md
Labels: bug, documentation

#597 QUA-370: Update "Checks Overview" file.
  docs/checks/overview-of-a-check.md
Labels: documentation, enhancement

#598 QUA-450: Remove the leading zeros in Change Log
  docs/changelog-2023.md
  docs/changelog-2024.md
  docs/changelog.md
Labels: documentation

#601 QUA-370: Update "Atlan" userguide as per the latest release.
  docs/assets/integrations/atlan/qualytics-global-settings-dark.png
  docs/assets/integrations/atlan/qualytics-global-settings-light.png
Labels: documentation

#599 QUA-370: Update "Identifiers" userguide as per the latest release.
  docs/assets/identifiers/identifiers-overview/datastore-dark.png
  docs/assets/identifiers/identifiers-overview/datastore-light.png
Labels: documentation

#603 QUA-451: Update "Scan Operation" userguide as per the latest release.
  docs/assets/datastores/scan/anomaly-option-dark.png
  docs/assets/datastores/scan/anomaly-option-light.png
  docs/assets/datastores/scan/anomalyy-dark.png
  docs/assets/datastores/scan/anomalyy-light.png
  docs/assets/datastores/scan/next-buttonn-dark.png
  docs/assets/datastores/scan/next-buttonn-light.png
  docs/assets/datastores/scan/scan-settings-dark.png
  docs/assets/datastores/scan/scan-settings-light.png
  docs/source-datastore/scan.md
Labels: documentation

#606 QUA-451: Update "Scan Operation" File as per the latest release.
  docs/source-datastore/scan.md
Labels: documentation
