Repository Qualytics/userguide, pull requests merged in 2025-01, with the labels that each got.

#417 Qua=156: Update "Azure blob Storage " file as per the latest release.
  docs/add-datastores/azure-blob-storage.md
  docs/assets/datastores/azure-blob-storage/add-datastore-credentials-dark.png
  docs/assets/datastores/azure-blob-storage/add-datastore-credentials-explain-dark.png
  docs/assets/datastores/azure-blob-storage/add-datastore-credentials-explain-light.png
  docs/assets/datastores/azure-blob-storage/add-datastore-credentials-light.png
  docs/assets/datastores/azure-blob-storage/add-datastore-dark.png
  docs/assets/datastores/azure-blob-storage/add-datastore-light.png
  docs/assets/datastores/azure-blob-storage/add-enrichment-details-dark-18.png
  docs/assets/datastores/azure-blob-storage/add-enrichment-details-light-18.png
  docs/assets/datastores/azure-blob-storage/data-operation-page-dark.png
  docs/assets/datastores/azure-blob-storage/data-operation-page-light.png
  docs/assets/datastores/azure-blob-storage/enrichment-datastore-explain-dark.png
  docs/assets/datastores/azure-blob-storage/enrichment-datastore-explain-light.png
  docs/assets/datastores/azure-blob-storage/enrichment-details-dark-11.png
  docs/assets/datastores/azure-blob-storage/enrichment-details-dark-9.png
  docs/assets/datastores/azure-blob-storage/enrichment-details-light-11.png
  docs/assets/datastores/azure-blob-storage/enrichment-details-light-9.png
  docs/assets/datastores/azure-blob-storage/finish-configuration-dark.png
  docs/assets/datastores/azure-blob-storage/finish-configuration-for-existing-enrichment-datastore-dark.png
  docs/assets/datastores/azure-blob-storage/finish-configuration-for-existing-enrichment-datastore-light.png
  docs/assets/datastores/azure-blob-storage/finish-configuration-light.png
  docs/assets/datastores/azure-blob-storage/next-button-for-enrichment-dark.png
  docs/assets/datastores/azure-blob-storage/next-button-for-enrichment-light.png
  docs/assets/datastores/azure-blob-storage/secret-management-dark-04.png
  docs/assets/datastores/azure-blob-storage/secret-management-light-04.png
  docs/assets/datastores/azure-blob-storage/select-a-connector-dark.png
  docs/assets/datastores/azure-blob-storage/select-a-connector-light.png
  docs/assets/datastores/azure-blob-storage/select-enrichment-dark-10.png
  docs/assets/datastores/azure-blob-storage/select-enrichment-dark-17.png
  docs/assets/datastores/azure-blob-storage/select-enrichment-light-10.png
  docs/assets/datastores/azure-blob-storage/select-enrichment-light-17.png
  docs/assets/datastores/azure-blob-storage/success-message-dark.png
  docs/assets/datastores/azure-blob-storage/success-message-light.png
  docs/assets/datastores/azure-blob-storage/test-connection-for-enrichment-datastore-dark.png
  docs/assets/datastores/azure-blob-storage/test-connection-for-enrichment-datastore-light.png
  docs/assets/datastores/azure-blob-storage/test-datastore-connection-dark.png
  docs/assets/datastores/azure-blob-storage/test-datastore-connection-light.png
  docs/assets/datastores/azure-blob-storage/use-existing-datastore-dark.png
  docs/assets/datastores/azure-blob-storage/use-existing-datastore-light.png
  docs/assets/datastores/azure-blob-storage/use-existing-enrichment-datastore-dark.png
  docs/assets/datastores/azure-blob-storage/use-existing-enrichment-datastore-light.png
Labels: documentation

#419 Qua-156: Update "Azure-datalake-storage-file" as per the latest release.
  docs/add-datastores/azure-datalake-storage.md
  docs/assets/datastores/azure-datalake-storage/add-datastore-credentials-dark.png
  docs/assets/datastores/azure-datalake-storage/add-datastore-credentials-explain-dark.png
  docs/assets/datastores/azure-datalake-storage/add-datastore-credentials-explain-light.png
  docs/assets/datastores/azure-datalake-storage/add-datastore-credentials-light.png
  docs/assets/datastores/azure-datalake-storage/add-datastore-dark.png
  docs/assets/datastores/azure-datalake-storage/add-datastore-light.png
  docs/assets/datastores/azure-datalake-storage/add-enrichment-details-dark-18.png
  docs/assets/datastores/azure-datalake-storage/add-enrichment-details-light-18.png
  docs/assets/datastores/azure-datalake-storage/data-operation-page-dark.png
  docs/assets/datastores/azure-datalake-storage/data-operation-page-light.png
  docs/assets/datastores/azure-datalake-storage/enrichment-datastore-explain-dark.png
  docs/assets/datastores/azure-datalake-storage/enrichment-datastore-explain-light.png
  docs/assets/datastores/azure-datalake-storage/enrichment-details-dark-11.png
  docs/assets/datastores/azure-datalake-storage/enrichment-details-light-11.png
  docs/assets/datastores/azure-datalake-storage/finish-configuration-dark.png
  docs/assets/datastores/azure-datalake-storage/finish-configuration-for-existing-enrichment-datastore-dark.png
  docs/assets/datastores/azure-datalake-storage/finish-configuration-for-existing-enrichment-datastore-light.png
  docs/assets/datastores/azure-datalake-storage/finish-configuration-light.png
  docs/assets/datastores/azure-datalake-storage/next-button-for-enrichment-dark.png
  docs/assets/datastores/azure-datalake-storage/next-button-for-enrichment-light.png
  docs/assets/datastores/azure-datalake-storage/page_23.png
  docs/assets/datastores/azure-datalake-storage/page_24.png
  docs/assets/datastores/azure-datalake-storage/secret-management-dark-04.png
  docs/assets/datastores/azure-datalake-storage/secret-management-light-04.png
  docs/assets/datastores/azure-datalake-storage/select-a-connector-dark.png
  docs/assets/datastores/azure-datalake-storage/select-a-connector-light.png
  docs/assets/datastores/azure-datalake-storage/select-enrichment-connector-dark.png
  docs/assets/datastores/azure-datalake-storage/select-enrichment-connector-light.png
  docs/assets/datastores/azure-datalake-storage/select-enrichment-dark-10.png
  docs/assets/datastores/azure-datalake-storage/select-enrichment-dark-17.png
  docs/assets/datastores/azure-datalake-storage/select-enrichment-light-10.png
  docs/assets/datastores/azure-datalake-storage/select-enrichment-light-17.png
  docs/assets/datastores/azure-datalake-storage/success-message-dark.png
  docs/assets/datastores/azure-datalake-storage/success-message-light.png
  docs/assets/datastores/azure-datalake-storage/test-connection-for-enrichment-datastore-dark.png
  docs/assets/datastores/azure-datalake-storage/test-connection-for-enrichment-datastore-light.png
  docs/assets/datastores/azure-datalake-storage/test-datastore-connection-dark.png
  docs/assets/datastores/azure-datalake-storage/test-datastore-connection-light.png
  docs/assets/datastores/azure-datalake-storage/use-existing-datastore-dark.png
  docs/assets/datastores/azure-datalake-storage/use-existing-datastore-light.png
  docs/assets/datastores/azure-datalake-storage/use-existing-enrichment-datastore-dark.png
  docs/assets/datastores/azure-datalake-storage/use-existing-enrichment-datastore-light.png
Labels: documentation

#420 Qua-156: Update "Google Cloud Storage" file as per the latest release.
  docs/add-datastores/google-cloud-storage.md
  docs/assets/datastores/google-cloud-storage/add-datastore-credentials-dark.png
  docs/assets/datastores/google-cloud-storage/add-datastore-credentials-explain-dark.png
  docs/assets/datastores/google-cloud-storage/add-datastore-credentials-explain-light.png
  docs/assets/datastores/google-cloud-storage/add-datastore-credentials-light.png
  docs/assets/datastores/google-cloud-storage/add-datastore-dark.png
  docs/assets/datastores/google-cloud-storage/add-datastore-light.png
  docs/assets/datastores/google-cloud-storage/add-enrichment-details-dark-18.png
  docs/assets/datastores/google-cloud-storage/add-enrichment-details-light-18.png
  docs/assets/datastores/google-cloud-storage/data-operation-page-dark.png
  docs/assets/datastores/google-cloud-storage/data-operation-page-light.png
  docs/assets/datastores/google-cloud-storage/enrichment-datastore-explain-dark.png
  docs/assets/datastores/google-cloud-storage/enrichment-datastore-explain-light.png
  docs/assets/datastores/google-cloud-storage/enrichment-details-dark-11.png
  docs/assets/datastores/google-cloud-storage/enrichment-details-light-11.png
  docs/assets/datastores/google-cloud-storage/finish-configuration-dark.png
  docs/assets/datastores/google-cloud-storage/finish-configuration-for-existing-enrichment-datastore-dark.png
  docs/assets/datastores/google-cloud-storage/finish-configuration-for-existing-enrichment-datastore-light.png
  docs/assets/datastores/google-cloud-storage/finish-configuration-light.png
  docs/assets/datastores/google-cloud-storage/next-button-for-enrichment-dark.png
  docs/assets/datastores/google-cloud-storage/next-button-for-enrichment-light.png
  docs/assets/datastores/google-cloud-storage/secret-management-dark-04.png
  docs/assets/datastores/google-cloud-storage/secret-management-light-04.png
  docs/assets/datastores/google-cloud-storage/select-a-connector-dark.png
  docs/assets/datastores/google-cloud-storage/select-a-connector-light.png
  docs/assets/datastores/google-cloud-storage/select-enrichment-connector-dark.png
  docs/assets/datastores/google-cloud-storage/select-enrichment-connector-light.png
  docs/assets/datastores/google-cloud-storage/select-enrichment-dark-10.png
  docs/assets/datastores/google-cloud-storage/select-enrichment-dark-17.png
  docs/assets/datastores/google-cloud-storage/select-enrichment-light-10.png
  docs/assets/datastores/google-cloud-storage/select-enrichment-light-17.png
  docs/assets/datastores/google-cloud-storage/success-message-dark.png
  docs/assets/datastores/google-cloud-storage/success-message-light.png
  docs/assets/datastores/google-cloud-storage/test-connection-for-enrichment-datastore-dark.png
  docs/assets/datastores/google-cloud-storage/test-connection-for-enrichment-datastore-light.png
  docs/assets/datastores/google-cloud-storage/test-connection-for-existing-datastore-dark.png
  docs/assets/datastores/google-cloud-storage/test-connection-for-existing-datastore-light.png
  docs/assets/datastores/google-cloud-storage/test-datastore-connection-dark.png
  docs/assets/datastores/google-cloud-storage/test-datastore-connection-light.png
  docs/assets/datastores/google-cloud-storage/use-existing-datastore-dark.png
  docs/assets/datastores/google-cloud-storage/use-existing-datastore-light.png
  docs/assets/datastores/google-cloud-storage/use-existing-enrichment-datastore-dark.png
  docs/assets/datastores/google-cloud-storage/use-existing-enrichment-datastore-light.png
Labels: documentation

#421 Qua-156: Update "Integrations Overview" File.
  docs/assets/integrations/overview/add-integration-button-dark.png
  docs/assets/integrations/overview/add-integration-button-light.png
  docs/assets/integrations/overview/event-dark.png
  docs/assets/integrations/overview/event-light.png
  docs/assets/integrations/overview/mannual-dark.png
  docs/assets/integrations/overview/mannual-light.png
  docs/assets/integrations/overview/setting-button-dark.png
  docs/assets/integrations/overview/setting-button-light.png
  docs/assets/integrations/overview/tab-button-dark.png
  docs/assets/integrations/overview/tab-button-light.png
  docs/settings/integrations/overview.md
Labels: documentation

#422 Qua-156: Update "Observability" File.
  docs/observability/observability.md
Labels: documentation

#423 Qua-156: Fix the broken links in "Overview" file
  docs/explore/overview-of-explore.md
Labels: bug, documentation

#429 Qua:156- Update "Profile Operation" file as per the latest release.
  docs/assets/profile-operations/adding-source-datastore-dark.png
  docs/assets/profile-operations/adding-source-datastore-light.png
Labels: documentation

#430 Qua-156: Update "Scan Operation" File as per the latest release.
  docs/assets/datastores/scan/side-menu-dark.png
  docs/assets/datastores/scan/side-menu-light.png
Labels: documentation

#431 Qua156: Update "Datastore Settings"File as per the latest release.
  docs/assets/datastore-settings/teams-dark-1.png
  docs/assets/datastore-settings/teams-light-1.png
  docs/source-datastore/datastore-settings.md
Labels: documentation

#433 Qua156: Update "Computed Field" file.
  docs/assets/container/computed-field/team-dark.png
  docs/assets/container/computed-field/team-light.png
  docs/container/overview-of-a-computed-field.md
Labels: documentation

#434 Qua156: Update "Overview" userguide.
  docs/checks/overview-of-a-check.md
Labels: documentation

#435 Qua156: Update "Catalog Operation" file .
  docs/assets/catalog-operations/add-source-datastore-dark.png
  docs/assets/catalog-operations/add-source-datastore-light.png
  docs/assets/catalog-operations/catalog-dark.png
  docs/assets/catalog-operations/catalog-light.png
Labels: documentation

#447 QUA-226: RC 2025.01.16
  docs/changelog.md
Labels: documentation

#438 Qua156: Update "MariaDB" file as per the latest release.
  docs/add-datastores/maria-db.md
  docs/assets/datastores/maria-db/Untitled document (2).pdf-image-042.png
  docs/assets/datastores/maria-db/Untitled document (2).pdf-image-043.png
  docs/assets/datastores/maria-db/Untitled document (2).pdf-image-044.png
  docs/assets/datastores/maria-db/Untitled document (2).pdf-image-045.png
  docs/assets/datastores/maria-db/add-dark.png
  docs/assets/datastores/maria-db/add-light.png
  docs/assets/datastores/maria-db/caret-dark.png
  docs/assets/datastores/maria-db/caret-light.png
  docs/assets/datastores/maria-db/carett-dark.png
  docs/assets/datastores/maria-db/carett-light.png
  docs/assets/datastores/maria-db/connections-dark.png
  docs/assets/datastores/maria-db/connections-light.png
  docs/assets/datastores/maria-db/connector-dark.png
  docs/assets/datastores/maria-db/connector-light.png
  docs/assets/datastores/maria-db/datastore-dark.png
  docs/assets/datastores/maria-db/datastore-light.png
  docs/assets/datastores/maria-db/details-dark.png
  docs/assets/datastores/maria-db/details-light.png
  docs/assets/datastores/maria-db/enrichmnet-dark.png
  docs/assets/datastores/maria-db/enrichmnet-light.png
  docs/assets/datastores/maria-db/finish-dark.png
  docs/assets/datastores/maria-db/finish-light.png
  docs/assets/datastores/maria-db/finishh-dark.png
  docs/assets/datastores/maria-db/finishh-light.png
  docs/assets/datastores/maria-db/form-dark.png
  docs/assets/datastores/maria-db/form-light.png
  docs/assets/datastores/maria-db/modal-dark.png
  docs/assets/datastores/maria-db/modal-light.png
  docs/assets/datastores/maria-db/msg-dark.png
  docs/assets/datastores/maria-db/msg-light.png
  docs/assets/datastores/maria-db/next-dark.png
  docs/assets/datastores/maria-db/next-light.png
  docs/assets/datastores/maria-db/operatons-dark.png
  docs/assets/datastores/maria-db/operatons-light.png
  docs/assets/datastores/maria-db/secret-dark.png
  docs/assets/datastores/maria-db/secret-light.png
  docs/assets/datastores/maria-db/test-dark.png
  docs/assets/datastores/maria-db/test-light.png
  docs/assets/datastores/maria-db/tests-dark.png
  docs/assets/datastores/maria-db/tests-light.png
  docs/assets/datastores/maria-db/testss-dark.png
  docs/assets/datastores/maria-db/testss-light.png
  docs/assets/datastores/maria-db/windoww-dark.png
  docs/assets/datastores/maria-db/windoww-light.png
  docs/assets/datastores/maria-db/windowww-dark.png
  docs/assets/datastores/maria-db/windowww-light.png
Labels: documentation

#439 Qua-204: Update "quick-start-guide" as per the latest release.
  docs/assets/quick-start-guide/authored-check-details-dark.png
  docs/assets/quick-start-guide/authored-check-details-light.png
  docs/assets/quick-start-guide/catalog-operation-dark.png
  docs/assets/quick-start-guide/catalog-operation-light.png
  docs/assets/quick-start-guide/check-template-details-dark.png
  docs/assets/quick-start-guide/check-template-details-light.png
  docs/assets/quick-start-guide/explore-activity-dark.png
  docs/assets/quick-start-guide/explore-activity-light.png
  docs/assets/quick-start-guide/explore-anomalies-dark.png
  docs/assets/quick-start-guide/explore-anomalies-light.png
  docs/assets/quick-start-guide/explore-checks-dark.png
  docs/assets/quick-start-guide/explore-checks-light.png
  docs/assets/quick-start-guide/explore-insights-dark.png
  docs/assets/quick-start-guide/explore-insights-light.png
  docs/assets/quick-start-guide/explore-profiles-dark.png
  docs/assets/quick-start-guide/explore-profiles-light.png
  docs/assets/quick-start-guide/export-check-templates-dark.png
  docs/assets/quick-start-guide/export-check-templates-light.png
  docs/assets/quick-start-guide/inferred-check-details-dark.png
  docs/assets/quick-start-guide/inferred-check-details-light.png
  docs/assets/quick-start-guide/observability-dark.png
  docs/assets/quick-start-guide/observability-light.png
  docs/assets/quick-start-guide/profile-operation-dark.png
  docs/assets/quick-start-guide/profile-operation-light.png
  docs/assets/quick-start-guide/scan-operation-dark.png
  docs/assets/quick-start-guide/scan-operation-light.png
  docs/assets/quick-start-guide/settings-connections-dark.png
  docs/assets/quick-start-guide/settings-connections-light.png
  docs/assets/quick-start-guide/settings-health-dark.png
  docs/assets/quick-start-guide/settings-health-light.png
  docs/assets/quick-start-guide/settings-integrations-dark.png
  docs/assets/quick-start-guide/settings-integrations-light.png
  docs/assets/quick-start-guide/settings-notifications-dark.png
  docs/assets/quick-start-guide/settings-notifications-light.png
  docs/assets/quick-start-guide/settings-security-dark.png
  docs/assets/quick-start-guide/settings-security-light.png
  docs/assets/quick-start-guide/settings-tags-dark.png
  docs/assets/quick-start-guide/settings-tags-light.png
  docs/assets/quick-start-guide/settings-tokens-dark.png
  docs/assets/quick-start-guide/settings-tokens-light.png
  docs/quick-start-guide.md
Labels: documentation

#440 Qua156: Update "Trino" File as per the latest release.
  docs/add-datastores/trino.md
  docs/assets/datastores/trino/Untitled document (3).pdf-image-042.png
  docs/assets/datastores/trino/Untitled document (3).pdf-image-043.png
  docs/assets/datastores/trino/Untitled document (3).pdf-image-044.png
  docs/assets/datastores/trino/Untitled document (3).pdf-image-045.png
  docs/assets/datastores/trino/caret-dark.png
  docs/assets/datastores/trino/caret-light.png
  docs/assets/datastores/trino/carett-dark.png
  docs/assets/datastores/trino/carett-light.png
  docs/assets/datastores/trino/connect-dark.png
  docs/assets/datastores/trino/connect-light.png
  docs/assets/datastores/trino/datastore-dark.png
  docs/assets/datastores/trino/datastore-light.png
  docs/assets/datastores/trino/detail-dark.png
  docs/assets/datastores/trino/detail-light.png
  docs/assets/datastores/trino/existing-dark.png
  docs/assets/datastores/trino/existing-light.png
  docs/assets/datastores/trino/finish-dark.png
  docs/assets/datastores/trino/finish-light.png
  docs/assets/datastores/trino/finishh-dark.png
  docs/assets/datastores/trino/finishh-light.png
  docs/assets/datastores/trino/form-dark.png
  docs/assets/datastores/trino/form-light.png
  docs/assets/datastores/trino/modall-dark.png
  docs/assets/datastores/trino/modall-light.png
  docs/assets/datastores/trino/msg-dark.png
  docs/assets/datastores/trino/msg-light.png
  docs/assets/datastores/trino/next-dark.png
  docs/assets/datastores/trino/next-light.png
  docs/assets/datastores/trino/operation-dark.png
  docs/assets/datastores/trino/operation-light.png
  docs/assets/datastores/trino/secret-dark.png
  docs/assets/datastores/trino/secret-light.png
  docs/assets/datastores/trino/select-dark.png
  docs/assets/datastores/trino/select-light.png
  docs/assets/datastores/trino/selectedd-dark.png
  docs/assets/datastores/trino/selectedd-light.png
  docs/assets/datastores/trino/test-dark.png
  docs/assets/datastores/trino/test-light.png
  docs/assets/datastores/trino/testt-dark.png
  docs/assets/datastores/trino/testt-light.png
  docs/assets/datastores/trino/testtt-dark.png
  docs/assets/datastores/trino/testtt-light.png
  docs/assets/datastores/trino/window-dark.png
  docs/assets/datastores/trino/window-light.png
  docs/assets/datastores/trino/windoww-dark.png
  docs/assets/datastores/trino/windoww-light.png
Labels: documentation

#442 qua-214-update synapse user guide as per the latest release
  docs/add-datastores/synapse.md
  docs/assets/datastores/synapse/add-dark.png
  docs/assets/datastores/synapse/add-datastore-dark.png
  docs/assets/datastores/synapse/add-datastore-light.png
  docs/assets/datastores/synapse/add-enrichment-datastore-2-dark.png
  docs/assets/datastores/synapse/add-enrichment-datastore-2-light.png
  docs/assets/datastores/synapse/add-enrichment-datastore-dark.png
  docs/assets/datastores/synapse/add-enrichment-datastore-light.png
  docs/assets/datastores/synapse/add-light.png
  docs/assets/datastores/synapse/credential-dark.png
  docs/assets/datastores/synapse/credential-light.png
  docs/assets/datastores/synapse/datastore-added-dark.png
  docs/assets/datastores/synapse/datastore-added-light.png
  docs/assets/datastores/synapse/datastore-created-dark.png
  docs/assets/datastores/synapse/datastore-created-light.png
  docs/assets/datastores/synapse/enrichment-datastore-connector-dark.png
  docs/assets/datastores/synapse/enrichment-datastore-connector-light.png
  docs/assets/datastores/synapse/enrichment-detail-dark.png
  docs/assets/datastores/synapse/enrichment-detail-light.png
  docs/assets/datastores/synapse/existing-credentials-dark.png
  docs/assets/datastores/synapse/existing-credentials-light.png
  docs/assets/datastores/synapse/finish-2-dark.png
  docs/assets/datastores/synapse/finish-2-light.png
  docs/assets/datastores/synapse/finish-dark.png
  docs/assets/datastores/synapse/finish-light.png
  docs/assets/datastores/synapse/link-enrichment-datastore-2-dark.png
  docs/assets/datastores/synapse/link-enrichment-datastore-2-light.png
  docs/assets/datastores/synapse/link-enrichment-datastore-dark.png
  docs/assets/datastores/synapse/link-enrichment-datastore-light.png
  docs/assets/datastores/synapse/next-dark.png
  docs/assets/datastores/synapse/next-light.png
  docs/assets/datastores/synapse/overview-2-dark.png
  docs/assets/datastores/synapse/overview-2-light.png
  docs/assets/datastores/synapse/overview-dark.png
  docs/assets/datastores/synapse/overview-light.png
  docs/assets/datastores/synapse/secret-management-dark.png
  docs/assets/datastores/synapse/secret-management-light.png
  docs/assets/datastores/synapse/synapse-connector-dark.png
  docs/assets/datastores/synapse/synapse-connector-light.png
  docs/assets/datastores/synapse/test-connection-2-dark.png
  docs/assets/datastores/synapse/test-connection-2-light.png
  docs/assets/datastores/synapse/test-connection-3-dark.png
  docs/assets/datastores/synapse/test-connection-3-light.png
  docs/assets/datastores/synapse/test-connection-dark.png
  docs/assets/datastores/synapse/test-connection-light.png
  docs/assets/datastores/synapse/use-enrichment-datastore-dark.png
  docs/assets/datastores/synapse/use-enrichment-datastore-light.png
Labels: documentation

#443 Qua-235: Update Qualytics file system userguide
  docs/add-datastores/qfs.md
  docs/assets/datastores/qfs/add-connection-dark.png
  docs/assets/datastores/qfs/add-connection-light.png
  docs/assets/datastores/qfs/add-datastore-dark.png
  docs/assets/datastores/qfs/add-datastore-light.png
  docs/assets/datastores/qfs/add-enrichment-datastore-dark.png
  docs/assets/datastores/qfs/add-enrichment-datastore-light.png
  docs/assets/datastores/qfs/datastore-dark.png
  docs/assets/datastores/qfs/datastore-light.png
  docs/assets/datastores/qfs/datastore-properties-dark.png
  docs/assets/datastores/qfs/datastore-properties-light.png
  docs/assets/datastores/qfs/detail-dark.png
  docs/assets/datastores/qfs/detail-light.png
  docs/assets/datastores/qfs/existing-credential-dark.png
  docs/assets/datastores/qfs/existing-credential-light.png
  docs/assets/datastores/qfs/finish-2-dark.png
  docs/assets/datastores/qfs/finish-2-light.png
  docs/assets/datastores/qfs/finish-dark.png
  docs/assets/datastores/qfs/finish-light.png
  docs/assets/datastores/qfs/link-enrichment-datastore-2-dark.png
  docs/assets/datastores/qfs/link-enrichment-datastore-2-light.png
  docs/assets/datastores/qfs/link-enrichment-datastore-3-dark.png
  docs/assets/datastores/qfs/link-enrichment-datastore-3-light.png
  docs/assets/datastores/qfs/link-enrichment-datastore-dark.png
  docs/assets/datastores/qfs/link-enrichment-datastore-light.png
  docs/assets/datastores/qfs/next-dark.png
  docs/assets/datastores/qfs/next-light.png
  docs/assets/datastores/qfs/overview-2-dark.png
  docs/assets/datastores/qfs/overview-2-light.png
  docs/assets/datastores/qfs/overview-dark.png
  docs/assets/datastores/qfs/overview-light.png
  docs/assets/datastores/qfs/secrets-management-dark.png
  docs/assets/datastores/qfs/secrets-management-light.png
  docs/assets/datastores/qfs/source-datastore-dark.png
  docs/assets/datastores/qfs/source-datastore-light.png
  docs/assets/datastores/qfs/success-2-dark.png
  docs/assets/datastores/qfs/success-2-light.png
  docs/assets/datastores/qfs/success-dark.png
  docs/assets/datastores/qfs/success-light.png
  docs/assets/datastores/qfs/test-2-dark.png
  docs/assets/datastores/qfs/test-2-light.png
  docs/assets/datastores/qfs/test-3-dark.png
  docs/assets/datastores/qfs/test-3-light.png
  docs/assets/datastores/qfs/test-dark.png
  docs/assets/datastores/qfs/test-light.png
  docs/assets/datastores/qfs/use-enrichment-datastore-dark.png
  docs/assets/datastores/qfs/use-enrichment-datastore-light.png
Labels: documentation

#444 Qua-236: Update "Manage Notification" userguide
  docs/assets/notifications/manage-notifications/bell-icon-dark-1.png
  docs/assets/notifications/manage-notifications/bell-icon-dark-21.png
  docs/assets/notifications/manage-notifications/bell-icon-dark-7.png
  docs/assets/notifications/manage-notifications/bell-icon-light-1.png
  docs/assets/notifications/manage-notifications/bell-icon-light-21.png
  docs/assets/notifications/manage-notifications/bell-icon-light-7.png
  docs/assets/notifications/manage-notifications/edit-button-dark-10.png
  docs/assets/notifications/manage-notifications/edit-button-light-10.png
  docs/assets/notifications/manage-notifications/mute-button-dark-24.png
  docs/assets/notifications/manage-notifications/mute-button-light-24.png
  docs/assets/notifications/manage-notifications/muted-notifi-dark-25.png
  docs/assets/notifications/manage-notifications/muted-notifi-light-25.png
  docs/assets/notifications/manage-notifications/notification-categorized-dark-3.png
  docs/assets/notifications/manage-notifications/notification-categorized-light-3.png
  docs/assets/notifications/manage-notifications/notification-rule-dark-14.png
  docs/assets/notifications/manage-notifications/notification-rule-dark-26.png
  docs/assets/notifications/manage-notifications/notification-rule-dark-33.png
  docs/assets/notifications/manage-notifications/notification-rule-dark-4.png
  docs/assets/notifications/manage-notifications/notification-rule-light-14.png
  docs/assets/notifications/manage-notifications/notification-rule-light-26.png
  docs/assets/notifications/manage-notifications/notification-rule-light-33.png
  docs/assets/notifications/manage-notifications/notification-rule-light-4.png
  docs/assets/notifications/manage-notifications/notification-triggered-dark-2.png
  docs/assets/notifications/manage-notifications/notification-triggered-dark-22.png
  docs/assets/notifications/manage-notifications/notification-triggered-dark-8.png
  docs/assets/notifications/manage-notifications/notification-triggered-light-2.png
  docs/assets/notifications/manage-notifications/notification-triggered-light-22.png
  docs/assets/notifications/manage-notifications/notification-triggered-light-8.png
  docs/assets/notifications/manage-notifications/vertical-ellipsis-dark-23.png
  docs/assets/notifications/manage-notifications/vertical-ellipsis-dark-9.png
  docs/assets/notifications/manage-notifications/vertical-ellipsis-light-23.png
  docs/assets/notifications/manage-notifications/vertical-ellipsis-light-9.png
Labels: documentation

#445 Qua-156: Update "Catalog operation" userguide
  docs/assets/catalog-operations/activity-calender-dark.png
  docs/assets/catalog-operations/activity-calender-light.png
  docs/assets/catalog-operations/activity-dark.png
  docs/assets/catalog-operations/activity-light.png
  docs/assets/catalog-operations/add-source-datastore-dark.png
  docs/assets/catalog-operations/add-source-datastore-light.png
  docs/assets/catalog-operations/completed-catalog-dark.png
  docs/assets/catalog-operations/completed-catalog-light.png
Labels: documentation

#446 Qua-156: Update "jdbc datastore overview" userguide
  docs/add-datastores/overview-of-a-jdbc-datastore.md
  docs/assets/datastores/jdbc-datastores/add-datastore-dark.png
  docs/assets/datastores/jdbc-datastores/add-datastore-light.png
  docs/assets/datastores/jdbc-datastores/catalog-dark.png
  docs/assets/datastores/jdbc-datastores/catalog-light.png
Labels: documentation

#450 QUA-266: RC 2025.01.20
  docs/changelog.md
Labels: documentation, enhancement

#448 Qua-156: Update quick start guide in user guide
  docs/quick-start-guide.md
Labels: documentation

#428 Qua-156: Update "Token File" as per the latest release.
  docs/assets/tokens/enter-values-dark-5.png
  docs/assets/tokens/enter-values-light-5.png
  docs/assets/tokens/generate-token-dark-3.png
  docs/assets/tokens/generate-token-dark-6.png
  docs/assets/tokens/generate-token-light-3.png
  docs/assets/tokens/generate-token-light-6.png
  docs/assets/tokens/revoke-dark-8.png
  docs/assets/tokens/revoke-light-8.png
  docs/assets/tokens/token-detail-dark-4.png
  docs/assets/tokens/token-detail-light-4.png
  docs/settings/tokens/overview-of-tokens.md
Labels: documentation

#461 QUA-281: RC 2025.01.24
  docs/changelog.md
Labels: release notes

#467 Qua:156- Update "Container Overview" userguide to add new feature freshness.
  docs/container/container.md
Labels: documentation

#466 Qua-156: Update Catalog userguide as per the latest release
  docs/assets/catalog-operations/add-source-datastore-dark.png
  docs/assets/catalog-operations/add-source-datastore-light.png
Labels: documentation

#465 Qua-156: update assign tag userguide as per the latest release
  docs/assets/assign-tags/add-datastore-dark-1.png
  docs/assets/assign-tags/add-datastore-light-1.png
  docs/assets/assign-tags/assign-tag-dark-2.png
  docs/assets/assign-tags/assign-tag-light-2.png
Labels: documentation

#464 Qua-156: update link enrichment user guide as per the latest release
  docs/assets/enrichment/link-datastore/datastore-dark.png
  docs/assets/enrichment/link-datastore/datastore-light.png
Labels: documentation

#462 Qua-156: Update add enrichment userguide as per the latest release
  docs/assets/enrichment/add-enrichment/save-dark.png
  docs/assets/enrichment/add-enrichment/save-light.png
  docs/assets/enrichment/add-enrichment/save2-dark.png
  docs/assets/enrichment/add-enrichment/save2-light.png
  docs/assets/enrichment/add-enrichment/test-dark.png
  docs/assets/enrichment/add-enrichment/test-light.png
  docs/assets/enrichment/add-enrichment/test2-dark.png
  docs/assets/enrichment/add-enrichment/test2-light.png
  docs/enrichment/enrichment-datastore-creation.md
Labels: documentation

#457 Qua-246: Update "Link Enrichment Datastore" File .
  docs/source-datastore/associate-enrichment-datastore.md
Labels: documentation

#456 Qua-156: Update the web application user guide as per the latest release
  docs/assets/dashboard/enrichment-datastore-nav-dark.png
  docs/assets/dashboard/enrichment-datastore-nav-light.png
  docs/assets/dashboard/explore-nav-dark.png
  docs/assets/dashboard/explore-nav-light.png
  docs/assets/dashboard/flows-dark.png
  docs/assets/dashboard/flows-light.png
  docs/assets/dashboard/global-search-dark.png
  docs/assets/dashboard/global-search-light.png
  docs/assets/dashboard/global-settings-dark.png
  docs/assets/dashboard/global-settings-light.png
  docs/assets/dashboard/library-access-dark.png
  docs/assets/dashboard/library-access-light.png
  docs/assets/dashboard/nav-notification-dark.png
  docs/assets/dashboard/nav-notification-light.png
  docs/assets/dashboard/source-datastore-nav-dark.png
  docs/assets/dashboard/source-datastore-nav-light.png
  docs/assets/dashboard/tags-dark.png
  docs/assets/dashboard/tags-light.png
  docs/web-app.md
Labels: documentation

#474 Qua156: Update "Health" document as per the latest release.
  docs/assets/health/private-dark.png
  docs/assets/health/private-light.png
  docs/settings/health/overview-of-health.md
Labels: documentation

#468 Qua-156: Update "Flows" userguide as per the latest release.
  docs/assets/flows/added-dark.png
  docs/assets/flows/added-light.png
  docs/assets/flows/clone-dark.png
  docs/assets/flows/clone-light.png
  docs/assets/flows/exisiting-doc-dark.png
  docs/assets/flows/exisiting-doc-light.png
  docs/assets/flows/flow-msg-dark.png
  docs/assets/flows/flow-msg-light.png
  docs/assets/flows/manuall-flow-dark.png
  docs/assets/flows/manuall-flow-light.png
  docs/assets/flows/publishh-dark.png
  docs/assets/flows/publishh-light.png
  docs/assets/flows/verticall-dark.png
  docs/assets/flows/verticall-light.png
  docs/flows/flows.md
Labels: documentation

#469 Qua156: Update "Check Template" userguide as per the latest release.
  docs/assets/checks/add-check-template/library-dark-1.png
  docs/assets/checks/add-check-template/library-light-1.png
Labels: documentation

#470 Qua156: Update "Apply Check Template for Quality Check" as per the latest release.
  docs/assets/checks/apply-check-template-for-quality-check/library-dark-1.png
  docs/assets/checks/apply-check-template-for-quality-check/library-light-1.png
Labels: documentation

#471 Qua156: Update "Overview" userguide as per the latest release.
  docs/assets/explore/overview-of-explore/explore-dark.png
  docs/assets/explore/overview-of-explore/explore-light.png
Labels: documentation

#473 Qua156: Update "Volumetric Check" userguide
  docs/assets/checks/volumetric-check/absolute-dark-6.png
  docs/assets/checks/volumetric-check/absolute-light-6.png
  docs/assets/checks/volumetric-check/change-dark-7.png
  docs/assets/checks/volumetric-check/change-light-7.png
  docs/assets/checks/volumetric-check/check-dark-2.png
  docs/assets/checks/volumetric-check/check-light-2.png
  docs/assets/checks/volumetric-check/comparision-dark-5.png
  docs/assets/checks/volumetric-check/comparision-light-5.png
  docs/assets/checks/volumetric-check/datastore-dark-1.png
  docs/assets/checks/volumetric-check/datastore-light-1.png
  docs/assets/checks/volumetric-check/last-dark-13.png
  docs/assets/checks/volumetric-check/last-light-13.png
  docs/assets/checks/volumetric-check/max-dark-12.png
  docs/assets/checks/volumetric-check/max-light-12.png
  docs/assets/checks/volumetric-check/measurement-dark-9.png
  docs/assets/checks/volumetric-check/measurement-light-9.png
  docs/assets/checks/volumetric-check/min-dark-11.png
  docs/assets/checks/volumetric-check/min-light-11.png
  docs/assets/checks/volumetric-check/modal-dark-3.png
  docs/assets/checks/volumetric-check/modal-light-3.png
  docs/assets/checks/volumetric-check/msg-dark-15.png
  docs/assets/checks/volumetric-check/msg-light-15.png
  docs/assets/checks/volumetric-check/name-dark-4.png
  docs/assets/checks/volumetric-check/name-light-4.png
  docs/assets/checks/volumetric-check/percentage-dark-8.png
  docs/assets/checks/volumetric-check/percentage-light-8.png
  docs/assets/checks/volumetric-check/save-dark-16.png
  docs/assets/checks/volumetric-check/save-light-16.png
  docs/assets/checks/volumetric-check/success-dark-17.png
  docs/assets/checks/volumetric-check/success-light-17.png
  docs/assets/checks/volumetric-check/threshold-dark-10.png
  docs/assets/checks/volumetric-check/threshold-light-10.png
  docs/assets/checks/volumetric-check/validate-dark-14.png
  docs/assets/checks/volumetric-check/validate-light-14.png
  docs/checks/volumetric-check.md
Labels: documentation

#479 QUA-306: RC 2025.01.31
  docs/changelog.md
Labels: release notes
